---
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - stylecheck
    # - gocomposites
    - gosec
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.generated\\.go$"

run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  build-tags:
    - myTag

