experimental_monorepo_root = true

[env]
MISE_EXPERIMENTAL = 1

[tools]
go = "1.24"
golangci-lint = '1.64.5'
golangci-lint-langserver = '0.0.10'

[tasks.ci]
description = "Run all monorepo CI tasks"
run = "mise run //apps/...:ci"
