apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: castaway
resources:
  - namespace.yaml
  - ../../base/castaway-web
  - ../../base/castaway-discord-bot
  - ../../base/probst
  - web-configmap.yaml
  - bot-configmap.yaml
  - web-servicemonitor.yaml
  - bot-servicemonitor.yaml
  - public
patches:
  - path: web-patch.yaml
  - path: web-placement-patch.yaml
  - path: web-migration-hook-patch.yaml
  - path: web-migration-placement-patch.yaml
  - path: bot-patch.yaml
  - path: bot-placement-patch.yaml
  - path: probst-placement-patch.yaml
images:
  - name: ghcr.io/bry-guy/castaway-web
    newName: ghcr.io/bry-guy/castaway-web
    digest: sha256:ca5003a4cec781597b3d51c38bbc23e051a8de6d781e9178fa5e0ac5c0462552
  - name: ghcr.io/bry-guy/castaway-discord-bot
    newName: ghcr.io/bry-guy/castaway-discord-bot
    digest: sha256:3e26fdc44ef657001466ca34e15a00c2bdc0450f1f972a998757138f2cd970bd
  - name: ghcr.io/bry-guy/probst
    newName: ghcr.io/bry-guy/probst
    digest: sha256:0c74b412baedd4bf5a1e22f1bf57047ac32c8516e32dfa29127ef58905f697e1
