apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: castaway
resources:
  - namespace.yaml
  - ../../base/castaway-web
  - ../../base/castaway-discord-bot
  - web-configmap.yaml
  - bot-configmap.yaml
  - ingress-web.yaml
patches:
  - path: web-patch.yaml
  - path: web-placement-patch.yaml
  - path: web-migration-hook-patch.yaml
  - path: web-migration-placement-patch.yaml
  - path: bot-patch.yaml
  - path: bot-placement-patch.yaml
images:
  - name: ghcr.io/bry-guy/castaway-web
    newName: ghcr.io/bry-guy/castaway-web
    digest: sha256:94a755cbca388c157e158da027e6a48c34e6608efe446e58e5456a884ca6d624
  - name: ghcr.io/bry-guy/castaway-discord-bot
    newName: ghcr.io/bry-guy/castaway-discord-bot
    digest: sha256:c37f31570e5a6a48365039e51549a1f4ea4537dfd6b9c3de3b66e5f68ed831ef
