apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: castaway
resources:
  - namespace.yaml
  - ../../base/castaway-web
  - ../../base/castaway-discord-bot
  - web-configmap.yaml
  - bot-configmap.yaml
  - web-servicemonitor.yaml
  - bot-servicemonitor.yaml
  - public
patches:
  - path: web-patch.yaml
  - path: web-placement-patch.yaml
  - path: web-migration-hook-patch.yaml
  - path: web-migration-placement-patch.yaml
  - path: bot-patch.yaml
  - path: bot-placement-patch.yaml
images:
  - name: ghcr.io/bry-guy/castaway-web
    newName: ghcr.io/bry-guy/castaway-web
    digest: sha256:23c8ab50be3238ffa34560aa31619118d801c030b6609c6da57cbfa82b1f15fa
  - name: ghcr.io/bry-guy/castaway-discord-bot
    newName: ghcr.io/bry-guy/castaway-discord-bot
    digest: sha256:eaab924b52a07e49a7150d44eadd28950c49640e4cec37bdf9954e64dfef530f
