apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: castaway-web
  labels:
    app.kubernetes.io/name: castaway-web
    app.kubernetes.io/part-of: castaway
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: castaway-web
  namespaceSelector:
    matchNames:
      - castaway
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
