// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_occurrences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityOccurrence = `-- name: CreateActivityOccurrence :one
WITH resolved_activity AS (
    SELECT
        ia.id AS activity_internal_id,
        ia.public_id AS activity_id
    FROM instance_activities ia
    WHERE ia.public_id = $9
)
INSERT INTO activity_occurrences (
    activity_id,
    occurrence_type,
    name,
    effective_at,
    starts_at,
    ends_at,
    status,
    source_ref,
    metadata
)
SELECT
    activity_internal_id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
FROM resolved_activity
RETURNING
    public_id AS id,
    (SELECT activity_id FROM resolved_activity) AS activity_id,
    occurrence_type,
    name,
    effective_at,
    starts_at,
    ends_at,
    status,
    source_ref,
    metadata,
    created_at,
    updated_at
`

type CreateActivityOccurrenceParams struct {
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Status         string             `json:"status"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	Metadata       []byte             `json:"metadata"`
	ActivityID     pgtype.UUID        `json:"activity_id"`
}

type CreateActivityOccurrenceRow struct {
	ID             pgtype.UUID        `json:"id"`
	ActivityID     pgtype.UUID        `json:"activity_id"`
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Status         string             `json:"status"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateActivityOccurrence(ctx context.Context, arg CreateActivityOccurrenceParams) (CreateActivityOccurrenceRow, error) {
	row := q.db.QueryRow(ctx, createActivityOccurrence,
		arg.OccurrenceType,
		arg.Name,
		arg.EffectiveAt,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.SourceRef,
		arg.Metadata,
		arg.ActivityID,
	)
	var i CreateActivityOccurrenceRow
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.OccurrenceType,
		&i.Name,
		&i.EffectiveAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.SourceRef,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createActivityOccurrenceGroup = `-- name: CreateActivityOccurrenceGroup :one
WITH resolved_occurrence AS (
    SELECT
        ao.id AS activity_occurrence_internal_id,
        ao.public_id AS activity_occurrence_id,
        ia.instance_id
    FROM activity_occurrences ao
    JOIN instance_activities ia ON ia.id = ao.activity_id
    WHERE ao.public_id = $4
), resolved_group AS (
    SELECT
        pg.id AS participant_group_internal_id,
        pg.public_id AS participant_group_id
    FROM participant_groups pg
    JOIN resolved_occurrence ro ON ro.instance_id = pg.instance_id
    WHERE pg.public_id = $5
)
INSERT INTO activity_occurrence_groups (
    activity_occurrence_id,
    participant_group_id,
    role,
    result,
    metadata
)
SELECT
    ro.activity_occurrence_internal_id,
    rg.participant_group_internal_id,
    $1,
    $2,
    $3
FROM resolved_occurrence ro
CROSS JOIN resolved_group rg
RETURNING
    id,
    (SELECT activity_occurrence_id FROM resolved_occurrence) AS activity_occurrence_id,
    (SELECT participant_group_id FROM resolved_group) AS participant_group_id,
    role,
    result,
    metadata,
    created_at
`

type CreateActivityOccurrenceGroupParams struct {
	Role                 string      `json:"role"`
	Result               string      `json:"result"`
	Metadata             []byte      `json:"metadata"`
	ActivityOccurrenceID pgtype.UUID `json:"activity_occurrence_id"`
	ParticipantGroupID   pgtype.UUID `json:"participant_group_id"`
}

type CreateActivityOccurrenceGroupRow struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateActivityOccurrenceGroup(ctx context.Context, arg CreateActivityOccurrenceGroupParams) (CreateActivityOccurrenceGroupRow, error) {
	row := q.db.QueryRow(ctx, createActivityOccurrenceGroup,
		arg.Role,
		arg.Result,
		arg.Metadata,
		arg.ActivityOccurrenceID,
		arg.ParticipantGroupID,
	)
	var i CreateActivityOccurrenceGroupRow
	err := row.Scan(
		&i.ID,
		&i.ActivityOccurrenceID,
		&i.ParticipantGroupID,
		&i.Role,
		&i.Result,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createActivityOccurrenceParticipant = `-- name: CreateActivityOccurrenceParticipant :one
WITH resolved_occurrence AS (
    SELECT
        ao.id AS activity_occurrence_internal_id,
        ao.public_id AS activity_occurrence_id,
        ia.instance_id
    FROM activity_occurrences ao
    JOIN instance_activities ia ON ia.id = ao.activity_id
    WHERE ao.public_id = $4
), resolved_participant AS (
    SELECT
        p.id AS participant_internal_id,
        p.public_id AS participant_id
    FROM participants p
    JOIN resolved_occurrence ro ON ro.instance_id = p.instance_id
    WHERE p.public_id = $5
), resolved_group AS (
    SELECT
        pg.id AS participant_group_internal_id,
        pg.public_id AS participant_group_id
    FROM participant_groups pg
    JOIN resolved_occurrence ro ON ro.instance_id = pg.instance_id
    WHERE pg.public_id = $6
)
INSERT INTO activity_occurrence_participants (
    activity_occurrence_id,
    participant_id,
    participant_group_id,
    role,
    result,
    metadata
)
SELECT
    ro.activity_occurrence_internal_id,
    rp.participant_internal_id,
    rg.participant_group_internal_id,
    $1,
    $2,
    $3
FROM resolved_occurrence ro
CROSS JOIN resolved_participant rp
LEFT JOIN resolved_group rg ON TRUE
RETURNING
    id,
    (SELECT activity_occurrence_id FROM resolved_occurrence) AS activity_occurrence_id,
    (SELECT participant_id FROM resolved_participant) AS participant_id,
    (SELECT participant_group_id FROM resolved_group) AS participant_group_id,
    role,
    result,
    metadata,
    created_at
`

type CreateActivityOccurrenceParticipantParams struct {
	Role                 string      `json:"role"`
	Result               string      `json:"result"`
	Metadata             []byte      `json:"metadata"`
	ActivityOccurrenceID pgtype.UUID `json:"activity_occurrence_id"`
	ParticipantID        pgtype.UUID `json:"participant_id"`
	ParticipantGroupID   pgtype.UUID `json:"participant_group_id"`
}

type CreateActivityOccurrenceParticipantRow struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateActivityOccurrenceParticipant(ctx context.Context, arg CreateActivityOccurrenceParticipantParams) (CreateActivityOccurrenceParticipantRow, error) {
	row := q.db.QueryRow(ctx, createActivityOccurrenceParticipant,
		arg.Role,
		arg.Result,
		arg.Metadata,
		arg.ActivityOccurrenceID,
		arg.ParticipantID,
		arg.ParticipantGroupID,
	)
	var i CreateActivityOccurrenceParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ActivityOccurrenceID,
		&i.ParticipantID,
		&i.ParticipantGroupID,
		&i.Role,
		&i.Result,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getActivityOccurrence = `-- name: GetActivityOccurrence :one
SELECT
    ao.public_id AS id,
    ia.public_id AS activity_id,
    ao.occurrence_type,
    ao.name,
    ao.effective_at,
    ao.starts_at,
    ao.ends_at,
    ao.status,
    ao.source_ref,
    ao.metadata,
    ao.created_at,
    ao.updated_at
FROM activity_occurrences ao
JOIN instance_activities ia ON ia.id = ao.activity_id
WHERE ao.public_id = $1
`

type GetActivityOccurrenceRow struct {
	ID             pgtype.UUID        `json:"id"`
	ActivityID     pgtype.UUID        `json:"activity_id"`
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Status         string             `json:"status"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActivityOccurrence(ctx context.Context, id pgtype.UUID) (GetActivityOccurrenceRow, error) {
	row := q.db.QueryRow(ctx, getActivityOccurrence, id)
	var i GetActivityOccurrenceRow
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.OccurrenceType,
		&i.Name,
		&i.EffectiveAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.SourceRef,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivityOccurrenceParticipant = `-- name: GetActivityOccurrenceParticipant :one
SELECT
    aop.id,
    ao.public_id AS activity_occurrence_id,
    p.public_id AS participant_id,
    p.name AS participant_name,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    aop.role,
    aop.result,
    aop.metadata,
    aop.created_at
FROM activity_occurrence_participants aop
JOIN activity_occurrences ao ON ao.id = aop.activity_occurrence_id
JOIN participants p ON p.id = aop.participant_id
LEFT JOIN participant_groups pg ON pg.id = aop.participant_group_id
WHERE ao.public_id = $1
  AND p.public_id = $2
  AND aop.role = $3
`

type GetActivityOccurrenceParticipantParams struct {
	ActivityOccurrenceID pgtype.UUID `json:"activity_occurrence_id"`
	ParticipantID        pgtype.UUID `json:"participant_id"`
	Role                 string      `json:"role"`
}

type GetActivityOccurrenceParticipantRow struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantName      string             `json:"participant_name"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName pgtype.Text        `json:"participant_group_name"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetActivityOccurrenceParticipant(ctx context.Context, arg GetActivityOccurrenceParticipantParams) (GetActivityOccurrenceParticipantRow, error) {
	row := q.db.QueryRow(ctx, getActivityOccurrenceParticipant, arg.ActivityOccurrenceID, arg.ParticipantID, arg.Role)
	var i GetActivityOccurrenceParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ActivityOccurrenceID,
		&i.ParticipantID,
		&i.ParticipantName,
		&i.ParticipantGroupID,
		&i.ParticipantGroupName,
		&i.Role,
		&i.Result,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityOccurrenceGroups = `-- name: ListActivityOccurrenceGroups :many
SELECT
    aog.id,
    ao.public_id AS activity_occurrence_id,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    aog.role,
    aog.result,
    aog.metadata,
    aog.created_at
FROM activity_occurrence_groups aog
JOIN activity_occurrences ao ON ao.id = aog.activity_occurrence_id
JOIN participant_groups pg ON pg.id = aog.participant_group_id
WHERE ao.public_id = $1
ORDER BY pg.name ASC, aog.id ASC
`

type ListActivityOccurrenceGroupsRow struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName string             `json:"participant_group_name"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActivityOccurrenceGroups(ctx context.Context, activityOccurrenceID pgtype.UUID) ([]ListActivityOccurrenceGroupsRow, error) {
	rows, err := q.db.Query(ctx, listActivityOccurrenceGroups, activityOccurrenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityOccurrenceGroupsRow{}
	for rows.Next() {
		var i ListActivityOccurrenceGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityOccurrenceID,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.Role,
			&i.Result,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityOccurrenceParticipants = `-- name: ListActivityOccurrenceParticipants :many
SELECT
    aop.id,
    ao.public_id AS activity_occurrence_id,
    p.public_id AS participant_id,
    p.name AS participant_name,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    aop.role,
    aop.result,
    aop.metadata,
    aop.created_at
FROM activity_occurrence_participants aop
JOIN activity_occurrences ao ON ao.id = aop.activity_occurrence_id
JOIN participants p ON p.id = aop.participant_id
LEFT JOIN participant_groups pg ON pg.id = aop.participant_group_id
WHERE ao.public_id = $1
ORDER BY p.name ASC, aop.id ASC
`

type ListActivityOccurrenceParticipantsRow struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantName      string             `json:"participant_name"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName pgtype.Text        `json:"participant_group_name"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActivityOccurrenceParticipants(ctx context.Context, activityOccurrenceID pgtype.UUID) ([]ListActivityOccurrenceParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listActivityOccurrenceParticipants, activityOccurrenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityOccurrenceParticipantsRow{}
	for rows.Next() {
		var i ListActivityOccurrenceParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityOccurrenceID,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.Role,
			&i.Result,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityOccurrencesByActivity = `-- name: ListActivityOccurrencesByActivity :many
SELECT
    ao.public_id AS id,
    ia.public_id AS activity_id,
    ao.occurrence_type,
    ao.name,
    ao.effective_at,
    ao.starts_at,
    ao.ends_at,
    ao.status,
    ao.source_ref,
    ao.metadata,
    ao.created_at,
    ao.updated_at
FROM activity_occurrences ao
JOIN instance_activities ia ON ia.id = ao.activity_id
WHERE ia.public_id = $1
ORDER BY ao.effective_at ASC, ao.id ASC
`

type ListActivityOccurrencesByActivityRow struct {
	ID             pgtype.UUID        `json:"id"`
	ActivityID     pgtype.UUID        `json:"activity_id"`
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Status         string             `json:"status"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActivityOccurrencesByActivity(ctx context.Context, activityID pgtype.UUID) ([]ListActivityOccurrencesByActivityRow, error) {
	rows, err := q.db.Query(ctx, listActivityOccurrencesByActivity, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityOccurrencesByActivityRow{}
	for rows.Next() {
		var i ListActivityOccurrencesByActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.OccurrenceType,
			&i.Name,
			&i.EffectiveAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.SourceRef,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityOccurrencesByActivityAndStatus = `-- name: ListActivityOccurrencesByActivityAndStatus :many
SELECT
    ao.public_id AS id,
    ia.public_id AS activity_id,
    ao.occurrence_type,
    ao.name,
    ao.effective_at,
    ao.starts_at,
    ao.ends_at,
    ao.status,
    ao.source_ref,
    ao.metadata,
    ao.created_at,
    ao.updated_at
FROM activity_occurrences ao
JOIN instance_activities ia ON ia.id = ao.activity_id
WHERE ia.public_id = $1
  AND ao.status = $2
ORDER BY ao.effective_at ASC, ao.id ASC
`

type ListActivityOccurrencesByActivityAndStatusParams struct {
	ActivityID pgtype.UUID `json:"activity_id"`
	Status     string      `json:"status"`
}

type ListActivityOccurrencesByActivityAndStatusRow struct {
	ID             pgtype.UUID        `json:"id"`
	ActivityID     pgtype.UUID        `json:"activity_id"`
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Status         string             `json:"status"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActivityOccurrencesByActivityAndStatus(ctx context.Context, arg ListActivityOccurrencesByActivityAndStatusParams) ([]ListActivityOccurrencesByActivityAndStatusRow, error) {
	rows, err := q.db.Query(ctx, listActivityOccurrencesByActivityAndStatus, arg.ActivityID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityOccurrencesByActivityAndStatusRow{}
	for rows.Next() {
		var i ListActivityOccurrencesByActivityAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.OccurrenceType,
			&i.Name,
			&i.EffectiveAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.SourceRef,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantOccurrenceInvolvementByInstance = `-- name: ListParticipantOccurrenceInvolvementByInstance :many
SELECT
    ia.public_id AS activity_id,
    ia.activity_type,
    ia.name AS activity_name,
    ia.status AS activity_status,
    ia.starts_at AS activity_starts_at,
    ia.ends_at AS activity_ends_at,
    ia.metadata AS activity_metadata,
    ia.created_at AS activity_created_at,
    ia.updated_at AS activity_updated_at,
    ao.public_id AS occurrence_id,
    ao.occurrence_type,
    ao.name AS occurrence_name,
    ao.effective_at,
    ao.starts_at,
    ao.ends_at,
    ao.status AS occurrence_status,
    ao.source_ref,
    ao.metadata AS occurrence_metadata,
    ao.created_at AS occurrence_created_at,
    ao.updated_at AS occurrence_updated_at,
    aop.id AS occurrence_participant_result_id,
    p.public_id AS participant_id,
    aop.role,
    aop.result,
    aop.metadata AS participant_metadata,
    aop.created_at AS participant_created_at,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name
FROM activity_occurrence_participants aop
JOIN activity_occurrences ao ON ao.id = aop.activity_occurrence_id
JOIN instance_activities ia ON ia.id = ao.activity_id
JOIN instances i ON i.id = ia.instance_id
JOIN participants p ON p.id = aop.participant_id
LEFT JOIN participant_groups pg ON pg.id = aop.participant_group_id
WHERE i.public_id = $1
  AND p.public_id = $2
ORDER BY ia.starts_at ASC, ao.effective_at ASC, aop.id ASC
`

type ListParticipantOccurrenceInvolvementByInstanceParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

type ListParticipantOccurrenceInvolvementByInstanceRow struct {
	ActivityID                    pgtype.UUID        `json:"activity_id"`
	ActivityType                  string             `json:"activity_type"`
	ActivityName                  string             `json:"activity_name"`
	ActivityStatus                string             `json:"activity_status"`
	ActivityStartsAt              pgtype.Timestamptz `json:"activity_starts_at"`
	ActivityEndsAt                pgtype.Timestamptz `json:"activity_ends_at"`
	ActivityMetadata              []byte             `json:"activity_metadata"`
	ActivityCreatedAt             pgtype.Timestamptz `json:"activity_created_at"`
	ActivityUpdatedAt             pgtype.Timestamptz `json:"activity_updated_at"`
	OccurrenceID                  pgtype.UUID        `json:"occurrence_id"`
	OccurrenceType                string             `json:"occurrence_type"`
	OccurrenceName                string             `json:"occurrence_name"`
	EffectiveAt                   pgtype.Timestamptz `json:"effective_at"`
	StartsAt                      pgtype.Timestamptz `json:"starts_at"`
	EndsAt                        pgtype.Timestamptz `json:"ends_at"`
	OccurrenceStatus              string             `json:"occurrence_status"`
	SourceRef                     pgtype.Text        `json:"source_ref"`
	OccurrenceMetadata            []byte             `json:"occurrence_metadata"`
	OccurrenceCreatedAt           pgtype.Timestamptz `json:"occurrence_created_at"`
	OccurrenceUpdatedAt           pgtype.Timestamptz `json:"occurrence_updated_at"`
	OccurrenceParticipantResultID int64              `json:"occurrence_participant_result_id"`
	ParticipantID                 pgtype.UUID        `json:"participant_id"`
	Role                          string             `json:"role"`
	Result                        string             `json:"result"`
	ParticipantMetadata           []byte             `json:"participant_metadata"`
	ParticipantCreatedAt          pgtype.Timestamptz `json:"participant_created_at"`
	ParticipantGroupID            pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName          pgtype.Text        `json:"participant_group_name"`
}

func (q *Queries) ListParticipantOccurrenceInvolvementByInstance(ctx context.Context, arg ListParticipantOccurrenceInvolvementByInstanceParams) ([]ListParticipantOccurrenceInvolvementByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listParticipantOccurrenceInvolvementByInstance, arg.InstanceID, arg.ParticipantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantOccurrenceInvolvementByInstanceRow{}
	for rows.Next() {
		var i ListParticipantOccurrenceInvolvementByInstanceRow
		if err := rows.Scan(
			&i.ActivityID,
			&i.ActivityType,
			&i.ActivityName,
			&i.ActivityStatus,
			&i.ActivityStartsAt,
			&i.ActivityEndsAt,
			&i.ActivityMetadata,
			&i.ActivityCreatedAt,
			&i.ActivityUpdatedAt,
			&i.OccurrenceID,
			&i.OccurrenceType,
			&i.OccurrenceName,
			&i.EffectiveAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.OccurrenceStatus,
			&i.SourceRef,
			&i.OccurrenceMetadata,
			&i.OccurrenceCreatedAt,
			&i.OccurrenceUpdatedAt,
			&i.OccurrenceParticipantResultID,
			&i.ParticipantID,
			&i.Role,
			&i.Result,
			&i.ParticipantMetadata,
			&i.ParticipantCreatedAt,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivityOccurrenceStatusAndMetadata = `-- name: UpdateActivityOccurrenceStatusAndMetadata :one
UPDATE activity_occurrences ao
SET status = $1,
    ends_at = $2,
    metadata = $3,
    updated_at = NOW()
WHERE ao.public_id = $4
RETURNING
    ao.public_id AS id,
    (SELECT ia.public_id FROM instance_activities ia WHERE ia.id = ao.activity_id) AS activity_id,
    ao.occurrence_type,
    ao.name,
    ao.effective_at,
    ao.starts_at,
    ao.ends_at,
    ao.status,
    ao.source_ref,
    ao.metadata,
    ao.created_at,
    ao.updated_at
`

type UpdateActivityOccurrenceStatusAndMetadataParams struct {
	Status   string             `json:"status"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	Metadata []byte             `json:"metadata"`
	ID       pgtype.UUID        `json:"id"`
}

type UpdateActivityOccurrenceStatusAndMetadataRow struct {
	ID             pgtype.UUID        `json:"id"`
	ActivityID     pgtype.UUID        `json:"activity_id"`
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Status         string             `json:"status"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateActivityOccurrenceStatusAndMetadata(ctx context.Context, arg UpdateActivityOccurrenceStatusAndMetadataParams) (UpdateActivityOccurrenceStatusAndMetadataRow, error) {
	row := q.db.QueryRow(ctx, updateActivityOccurrenceStatusAndMetadata,
		arg.Status,
		arg.EndsAt,
		arg.Metadata,
		arg.ID,
	)
	var i UpdateActivityOccurrenceStatusAndMetadataRow
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.OccurrenceType,
		&i.Name,
		&i.EffectiveAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.SourceRef,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertActivityOccurrenceParticipant = `-- name: UpsertActivityOccurrenceParticipant :one
WITH resolved_occurrence AS (
    SELECT
        ao.id AS activity_occurrence_internal_id,
        ao.public_id AS activity_occurrence_id,
        ia.instance_id
    FROM activity_occurrences ao
    JOIN instance_activities ia ON ia.id = ao.activity_id
    WHERE ao.public_id = $4
), resolved_participant AS (
    SELECT
        p.id AS participant_internal_id,
        p.public_id AS participant_id
    FROM participants p
    JOIN resolved_occurrence ro ON ro.instance_id = p.instance_id
    WHERE p.public_id = $5
), resolved_group AS (
    SELECT
        pg.id AS participant_group_internal_id,
        pg.public_id AS participant_group_id
    FROM participant_groups pg
    JOIN resolved_occurrence ro ON ro.instance_id = pg.instance_id
    WHERE pg.public_id = $6
)
INSERT INTO activity_occurrence_participants (
    activity_occurrence_id,
    participant_id,
    participant_group_id,
    role,
    result,
    metadata
)
SELECT
    ro.activity_occurrence_internal_id,
    rp.participant_internal_id,
    rg.participant_group_internal_id,
    $1,
    $2,
    $3
FROM resolved_occurrence ro
CROSS JOIN resolved_participant rp
LEFT JOIN resolved_group rg ON TRUE
ON CONFLICT (activity_occurrence_id, participant_id, role)
DO UPDATE SET
    participant_group_id = EXCLUDED.participant_group_id,
    result = EXCLUDED.result,
    metadata = EXCLUDED.metadata
RETURNING
    id,
    (SELECT activity_occurrence_id FROM resolved_occurrence) AS activity_occurrence_id,
    (SELECT participant_id FROM resolved_participant) AS participant_id,
    (SELECT participant_group_id FROM resolved_group) AS participant_group_id,
    role,
    result,
    metadata,
    created_at
`

type UpsertActivityOccurrenceParticipantParams struct {
	Role                 string      `json:"role"`
	Result               string      `json:"result"`
	Metadata             []byte      `json:"metadata"`
	ActivityOccurrenceID pgtype.UUID `json:"activity_occurrence_id"`
	ParticipantID        pgtype.UUID `json:"participant_id"`
	ParticipantGroupID   pgtype.UUID `json:"participant_group_id"`
}

type UpsertActivityOccurrenceParticipantRow struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertActivityOccurrenceParticipant(ctx context.Context, arg UpsertActivityOccurrenceParticipantParams) (UpsertActivityOccurrenceParticipantRow, error) {
	row := q.db.QueryRow(ctx, upsertActivityOccurrenceParticipant,
		arg.Role,
		arg.Result,
		arg.Metadata,
		arg.ActivityOccurrenceID,
		arg.ParticipantID,
		arg.ParticipantGroupID,
	)
	var i UpsertActivityOccurrenceParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ActivityOccurrenceID,
		&i.ParticipantID,
		&i.ParticipantGroupID,
		&i.Role,
		&i.Result,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
