// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityGroupAssignment = `-- name: CreateActivityGroupAssignment :one
WITH resolved AS (
    SELECT
        ia.id AS activity_internal_id,
        pg.id AS participant_group_internal_id,
        ia.public_id AS activity_id,
        pg.public_id AS participant_group_id
    FROM instance_activities ia
    JOIN participant_groups pg ON pg.public_id = $5
       AND pg.instance_id = ia.instance_id
    WHERE ia.public_id = $6
)
INSERT INTO activity_group_assignments (
    activity_id,
    participant_group_id,
    role,
    starts_at,
    ends_at,
    configuration
)
SELECT
    activity_internal_id,
    participant_group_internal_id,
    $1,
    $2,
    $3,
    $4
FROM resolved
RETURNING
    id,
    (SELECT activity_id FROM resolved) AS activity_id,
    (SELECT participant_group_id FROM resolved) AS participant_group_id,
    role,
    starts_at,
    ends_at,
    configuration,
    created_at
`

type CreateActivityGroupAssignmentParams struct {
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Configuration      []byte             `json:"configuration"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	ActivityID         pgtype.UUID        `json:"activity_id"`
}

type CreateActivityGroupAssignmentRow struct {
	ID                 int64              `json:"id"`
	ActivityID         pgtype.UUID        `json:"activity_id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Configuration      []byte             `json:"configuration"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateActivityGroupAssignment(ctx context.Context, arg CreateActivityGroupAssignmentParams) (CreateActivityGroupAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createActivityGroupAssignment,
		arg.Role,
		arg.StartsAt,
		arg.EndsAt,
		arg.Configuration,
		arg.ParticipantGroupID,
		arg.ActivityID,
	)
	var i CreateActivityGroupAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ParticipantGroupID,
		&i.Role,
		&i.StartsAt,
		&i.EndsAt,
		&i.Configuration,
		&i.CreatedAt,
	)
	return i, err
}

const createActivityParticipantAssignment = `-- name: CreateActivityParticipantAssignment :one
WITH resolved_activity AS (
    SELECT
        ia.id AS activity_internal_id,
        ia.instance_id,
        ia.public_id AS activity_id
    FROM instance_activities ia
    WHERE ia.public_id = $5
), resolved_participant AS (
    SELECT
        p.id AS participant_internal_id,
        p.public_id AS participant_id
    FROM participants p
    JOIN resolved_activity ra ON ra.instance_id = p.instance_id
    WHERE p.public_id = $6
), resolved_group AS (
    SELECT
        pg.id AS participant_group_internal_id,
        pg.public_id AS participant_group_id
    FROM participant_groups pg
    JOIN resolved_activity ra ON ra.instance_id = pg.instance_id
    WHERE pg.public_id = $7
)
INSERT INTO activity_participant_assignments (
    activity_id,
    participant_id,
    participant_group_id,
    role,
    starts_at,
    ends_at,
    configuration
)
SELECT
    ra.activity_internal_id,
    rp.participant_internal_id,
    rg.participant_group_internal_id,
    $1,
    $2,
    $3,
    $4
FROM resolved_activity ra
CROSS JOIN resolved_participant rp
LEFT JOIN resolved_group rg ON TRUE
RETURNING
    id,
    (SELECT activity_id FROM resolved_activity) AS activity_id,
    (SELECT participant_id FROM resolved_participant) AS participant_id,
    (SELECT participant_group_id FROM resolved_group) AS participant_group_id,
    role,
    starts_at,
    ends_at,
    configuration,
    created_at
`

type CreateActivityParticipantAssignmentParams struct {
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Configuration      []byte             `json:"configuration"`
	ActivityID         pgtype.UUID        `json:"activity_id"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
}

type CreateActivityParticipantAssignmentRow struct {
	ID                 int64              `json:"id"`
	ActivityID         pgtype.UUID        `json:"activity_id"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Configuration      []byte             `json:"configuration"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateActivityParticipantAssignment(ctx context.Context, arg CreateActivityParticipantAssignmentParams) (CreateActivityParticipantAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createActivityParticipantAssignment,
		arg.Role,
		arg.StartsAt,
		arg.EndsAt,
		arg.Configuration,
		arg.ActivityID,
		arg.ParticipantID,
		arg.ParticipantGroupID,
	)
	var i CreateActivityParticipantAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.ParticipantID,
		&i.ParticipantGroupID,
		&i.Role,
		&i.StartsAt,
		&i.EndsAt,
		&i.Configuration,
		&i.CreatedAt,
	)
	return i, err
}

const createInstanceActivity = `-- name: CreateInstanceActivity :one
INSERT INTO instance_activities (
    instance_id,
    activity_type,
    name,
    status,
    starts_at,
    ends_at,
    metadata
)
SELECT
    i.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM instances i
WHERE i.public_id = $7
RETURNING
    public_id AS id,
    (SELECT public_id FROM instances WHERE id = instance_activities.instance_id) AS instance_id,
    activity_type,
    name,
    status,
    starts_at,
    ends_at,
    metadata,
    created_at,
    updated_at
`

type CreateInstanceActivityParams struct {
	ActivityType string             `json:"activity_type"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	Metadata     []byte             `json:"metadata"`
	InstanceID   pgtype.UUID        `json:"instance_id"`
}

type CreateInstanceActivityRow struct {
	ID           pgtype.UUID        `json:"id"`
	InstanceID   pgtype.UUID        `json:"instance_id"`
	ActivityType string             `json:"activity_type"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInstanceActivity(ctx context.Context, arg CreateInstanceActivityParams) (CreateInstanceActivityRow, error) {
	row := q.db.QueryRow(ctx, createInstanceActivity,
		arg.ActivityType,
		arg.Name,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
		arg.Metadata,
		arg.InstanceID,
	)
	var i CreateInstanceActivityRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ActivityType,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceActivity = `-- name: GetInstanceActivity :one
SELECT
    ia.public_id AS id,
    i.public_id AS instance_id,
    ia.activity_type,
    ia.name,
    ia.status,
    ia.starts_at,
    ia.ends_at,
    ia.metadata,
    ia.created_at,
    ia.updated_at
FROM instance_activities ia
JOIN instances i ON i.id = ia.instance_id
WHERE ia.public_id = $1
`

type GetInstanceActivityRow struct {
	ID           pgtype.UUID        `json:"id"`
	InstanceID   pgtype.UUID        `json:"instance_id"`
	ActivityType string             `json:"activity_type"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetInstanceActivity(ctx context.Context, id pgtype.UUID) (GetInstanceActivityRow, error) {
	row := q.db.QueryRow(ctx, getInstanceActivity, id)
	var i GetInstanceActivityRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ActivityType,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveActivityGroupAssignmentsAt = `-- name: ListActiveActivityGroupAssignmentsAt :many
SELECT
    aga.id,
    ia.public_id AS activity_id,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    aga.role,
    aga.starts_at,
    aga.ends_at,
    aga.configuration,
    aga.created_at
FROM activity_group_assignments aga
JOIN instance_activities ia ON ia.id = aga.activity_id
JOIN participant_groups pg ON pg.id = aga.participant_group_id
WHERE ia.public_id = $1
  AND aga.starts_at <= $2
  AND (aga.ends_at IS NULL OR aga.ends_at > $2)
ORDER BY pg.name ASC, aga.id ASC
`

type ListActiveActivityGroupAssignmentsAtParams struct {
	ActivityID pgtype.UUID        `json:"activity_id"`
	At         pgtype.Timestamptz `json:"at"`
}

type ListActiveActivityGroupAssignmentsAtRow struct {
	ID                   int64              `json:"id"`
	ActivityID           pgtype.UUID        `json:"activity_id"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName string             `json:"participant_group_name"`
	Role                 string             `json:"role"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	Configuration        []byte             `json:"configuration"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveActivityGroupAssignmentsAt(ctx context.Context, arg ListActiveActivityGroupAssignmentsAtParams) ([]ListActiveActivityGroupAssignmentsAtRow, error) {
	rows, err := q.db.Query(ctx, listActiveActivityGroupAssignmentsAt, arg.ActivityID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveActivityGroupAssignmentsAtRow{}
	for rows.Next() {
		var i ListActiveActivityGroupAssignmentsAtRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.Role,
			&i.StartsAt,
			&i.EndsAt,
			&i.Configuration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveActivityParticipantAssignmentsAt = `-- name: ListActiveActivityParticipantAssignmentsAt :many
SELECT
    apa.id,
    ia.public_id AS activity_id,
    p.public_id AS participant_id,
    p.name AS participant_name,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    apa.role,
    apa.starts_at,
    apa.ends_at,
    apa.configuration,
    apa.created_at
FROM activity_participant_assignments apa
JOIN instance_activities ia ON ia.id = apa.activity_id
JOIN participants p ON p.id = apa.participant_id
LEFT JOIN participant_groups pg ON pg.id = apa.participant_group_id
WHERE ia.public_id = $1
  AND apa.starts_at <= $2
  AND (apa.ends_at IS NULL OR apa.ends_at > $2)
ORDER BY p.name ASC, apa.id ASC
`

type ListActiveActivityParticipantAssignmentsAtParams struct {
	ActivityID pgtype.UUID        `json:"activity_id"`
	At         pgtype.Timestamptz `json:"at"`
}

type ListActiveActivityParticipantAssignmentsAtRow struct {
	ID                   int64              `json:"id"`
	ActivityID           pgtype.UUID        `json:"activity_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantName      string             `json:"participant_name"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName pgtype.Text        `json:"participant_group_name"`
	Role                 string             `json:"role"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	Configuration        []byte             `json:"configuration"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveActivityParticipantAssignmentsAt(ctx context.Context, arg ListActiveActivityParticipantAssignmentsAtParams) ([]ListActiveActivityParticipantAssignmentsAtRow, error) {
	rows, err := q.db.Query(ctx, listActiveActivityParticipantAssignmentsAt, arg.ActivityID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveActivityParticipantAssignmentsAtRow{}
	for rows.Next() {
		var i ListActiveActivityParticipantAssignmentsAtRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.Role,
			&i.StartsAt,
			&i.EndsAt,
			&i.Configuration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityGroupAssignments = `-- name: ListActivityGroupAssignments :many
SELECT
    aga.id,
    ia.public_id AS activity_id,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    aga.role,
    aga.starts_at,
    aga.ends_at,
    aga.configuration,
    aga.created_at
FROM activity_group_assignments aga
JOIN instance_activities ia ON ia.id = aga.activity_id
JOIN participant_groups pg ON pg.id = aga.participant_group_id
WHERE ia.public_id = $1
ORDER BY aga.starts_at ASC, aga.id ASC
`

type ListActivityGroupAssignmentsRow struct {
	ID                   int64              `json:"id"`
	ActivityID           pgtype.UUID        `json:"activity_id"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName string             `json:"participant_group_name"`
	Role                 string             `json:"role"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	Configuration        []byte             `json:"configuration"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActivityGroupAssignments(ctx context.Context, activityID pgtype.UUID) ([]ListActivityGroupAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listActivityGroupAssignments, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityGroupAssignmentsRow{}
	for rows.Next() {
		var i ListActivityGroupAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.Role,
			&i.StartsAt,
			&i.EndsAt,
			&i.Configuration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityParticipantAssignments = `-- name: ListActivityParticipantAssignments :many
SELECT
    apa.id,
    ia.public_id AS activity_id,
    p.public_id AS participant_id,
    p.name AS participant_name,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    apa.role,
    apa.starts_at,
    apa.ends_at,
    apa.configuration,
    apa.created_at
FROM activity_participant_assignments apa
JOIN instance_activities ia ON ia.id = apa.activity_id
JOIN participants p ON p.id = apa.participant_id
LEFT JOIN participant_groups pg ON pg.id = apa.participant_group_id
WHERE ia.public_id = $1
ORDER BY apa.starts_at ASC, apa.id ASC
`

type ListActivityParticipantAssignmentsRow struct {
	ID                   int64              `json:"id"`
	ActivityID           pgtype.UUID        `json:"activity_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantName      string             `json:"participant_name"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName pgtype.Text        `json:"participant_group_name"`
	Role                 string             `json:"role"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	Configuration        []byte             `json:"configuration"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActivityParticipantAssignments(ctx context.Context, activityID pgtype.UUID) ([]ListActivityParticipantAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listActivityParticipantAssignments, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityParticipantAssignmentsRow{}
	for rows.Next() {
		var i ListActivityParticipantAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.Role,
			&i.StartsAt,
			&i.EndsAt,
			&i.Configuration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceActivitiesByInstance = `-- name: ListInstanceActivitiesByInstance :many
SELECT
    ia.public_id AS id,
    i.public_id AS instance_id,
    ia.activity_type,
    ia.name,
    ia.status,
    ia.starts_at,
    ia.ends_at,
    ia.metadata,
    ia.created_at,
    ia.updated_at
FROM instance_activities ia
JOIN instances i ON i.id = ia.instance_id
WHERE i.public_id = $1
ORDER BY ia.starts_at ASC, ia.id ASC
`

type ListInstanceActivitiesByInstanceRow struct {
	ID           pgtype.UUID        `json:"id"`
	InstanceID   pgtype.UUID        `json:"instance_id"`
	ActivityType string             `json:"activity_type"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListInstanceActivitiesByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListInstanceActivitiesByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listInstanceActivitiesByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstanceActivitiesByInstanceRow{}
	for rows.Next() {
		var i ListInstanceActivitiesByInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ActivityType,
			&i.Name,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
