// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: advantages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipantAdvantage = `-- name: CreateParticipantAdvantage :one
WITH resolved_instance AS (
    SELECT i.id AS instance_internal_id, i.public_id AS instance_id
    FROM instances i
    WHERE i.public_id = $8
), resolved_participant AS (
    SELECT p.id AS participant_internal_id, p.public_id AS participant_id
    FROM participants p
    JOIN resolved_instance ri ON ri.instance_internal_id = p.instance_id
    WHERE p.public_id = $9
), resolved_group AS (
    SELECT pg.id AS group_internal_id, pg.public_id AS participant_group_id
    FROM participant_groups pg
    JOIN resolved_instance ri ON ri.instance_internal_id = pg.instance_id
    WHERE pg.public_id = $10
), resolved_occurrence AS (
    SELECT ao.id AS occurrence_internal_id, ao.public_id AS source_activity_occurrence_id
    FROM activity_occurrences ao
    JOIN instance_activities ia ON ia.id = ao.activity_id
    JOIN resolved_instance ri ON ri.instance_internal_id = ia.instance_id
    WHERE ao.public_id = $11
)
INSERT INTO participant_advantages (
    instance_id,
    participant_id,
    participant_group_id,
    advantage_type,
    name,
    status,
    source_activity_occurrence_id,
    granted_at,
    effective_at,
    effective_until,
    metadata
)
SELECT
    ri.instance_internal_id,
    rp.participant_internal_id,
    rg.group_internal_id,
    $1,
    $2,
    $3,
    ro.occurrence_internal_id,
    $4,
    $5,
    $6,
    $7
FROM resolved_instance ri
CROSS JOIN resolved_participant rp
LEFT JOIN resolved_group rg ON TRUE
LEFT JOIN resolved_occurrence ro ON TRUE
RETURNING
    public_id AS id,
    (SELECT instance_id FROM resolved_instance) AS instance_id,
    (SELECT participant_id FROM resolved_participant) AS participant_id,
    (SELECT participant_group_id FROM resolved_group) AS participant_group_id,
    advantage_type,
    name,
    status,
    (SELECT source_activity_occurrence_id FROM resolved_occurrence) AS source_activity_occurrence_id,
    granted_at,
    effective_at,
    effective_until,
    metadata,
    created_at,
    updated_at
`

type CreateParticipantAdvantageParams struct {
	AdvantageType              string             `json:"advantage_type"`
	Name                       string             `json:"name"`
	Status                     string             `json:"status"`
	GrantedAt                  pgtype.Timestamptz `json:"granted_at"`
	EffectiveAt                pgtype.Timestamptz `json:"effective_at"`
	EffectiveUntil             pgtype.Timestamptz `json:"effective_until"`
	Metadata                   []byte             `json:"metadata"`
	InstanceID                 pgtype.UUID        `json:"instance_id"`
	ParticipantID              pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID         pgtype.UUID        `json:"participant_group_id"`
	SourceActivityOccurrenceID pgtype.UUID        `json:"source_activity_occurrence_id"`
}

type CreateParticipantAdvantageRow struct {
	ID                         pgtype.UUID        `json:"id"`
	InstanceID                 pgtype.UUID        `json:"instance_id"`
	ParticipantID              pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID         pgtype.UUID        `json:"participant_group_id"`
	AdvantageType              string             `json:"advantage_type"`
	Name                       string             `json:"name"`
	Status                     string             `json:"status"`
	SourceActivityOccurrenceID pgtype.UUID        `json:"source_activity_occurrence_id"`
	GrantedAt                  pgtype.Timestamptz `json:"granted_at"`
	EffectiveAt                pgtype.Timestamptz `json:"effective_at"`
	EffectiveUntil             pgtype.Timestamptz `json:"effective_until"`
	Metadata                   []byte             `json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateParticipantAdvantage(ctx context.Context, arg CreateParticipantAdvantageParams) (CreateParticipantAdvantageRow, error) {
	row := q.db.QueryRow(ctx, createParticipantAdvantage,
		arg.AdvantageType,
		arg.Name,
		arg.Status,
		arg.GrantedAt,
		arg.EffectiveAt,
		arg.EffectiveUntil,
		arg.Metadata,
		arg.InstanceID,
		arg.ParticipantID,
		arg.ParticipantGroupID,
		arg.SourceActivityOccurrenceID,
	)
	var i CreateParticipantAdvantageRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ParticipantID,
		&i.ParticipantGroupID,
		&i.AdvantageType,
		&i.Name,
		&i.Status,
		&i.SourceActivityOccurrenceID,
		&i.GrantedAt,
		&i.EffectiveAt,
		&i.EffectiveUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAdvantagesByTypeForGroup = `-- name: ListActiveAdvantagesByTypeForGroup :many
SELECT
    pa.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    pg.public_id AS participant_group_id,
    pa.advantage_type,
    pa.name,
    pa.status,
    pa.granted_at,
    pa.effective_at,
    pa.effective_until,
    pa.metadata,
    pa.created_at,
    pa.updated_at
FROM participant_advantages pa
JOIN instances i ON i.id = pa.instance_id
JOIN participants p ON p.id = pa.participant_id
LEFT JOIN participant_groups pg ON pg.id = pa.participant_group_id
WHERE i.public_id = $1
  AND pg.public_id = $2
  AND pa.advantage_type = $3
  AND pa.status = 'active'
  AND pa.effective_at <= $4
  AND (pa.effective_until IS NULL OR pa.effective_until > $4)
ORDER BY pa.granted_at ASC
`

type ListActiveAdvantagesByTypeForGroupParams struct {
	InstanceID         pgtype.UUID        `json:"instance_id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	AdvantageType      string             `json:"advantage_type"`
	At                 pgtype.Timestamptz `json:"at"`
}

type ListActiveAdvantagesByTypeForGroupRow struct {
	ID                 pgtype.UUID        `json:"id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	AdvantageType      string             `json:"advantage_type"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	GrantedAt          pgtype.Timestamptz `json:"granted_at"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	EffectiveUntil     pgtype.Timestamptz `json:"effective_until"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveAdvantagesByTypeForGroup(ctx context.Context, arg ListActiveAdvantagesByTypeForGroupParams) ([]ListActiveAdvantagesByTypeForGroupRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdvantagesByTypeForGroup,
		arg.InstanceID,
		arg.ParticipantGroupID,
		arg.AdvantageType,
		arg.At,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdvantagesByTypeForGroupRow{}
	for rows.Next() {
		var i ListActiveAdvantagesByTypeForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ParticipantID,
			&i.ParticipantGroupID,
			&i.AdvantageType,
			&i.Name,
			&i.Status,
			&i.GrantedAt,
			&i.EffectiveAt,
			&i.EffectiveUntil,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAdvantagesByTypeForParticipant = `-- name: ListActiveAdvantagesByTypeForParticipant :many
SELECT
    pa.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    pg.public_id AS participant_group_id,
    pa.advantage_type,
    pa.name,
    pa.status,
    pa.granted_at,
    pa.effective_at,
    pa.effective_until,
    pa.metadata,
    pa.created_at,
    pa.updated_at
FROM participant_advantages pa
JOIN instances i ON i.id = pa.instance_id
JOIN participants p ON p.id = pa.participant_id
LEFT JOIN participant_groups pg ON pg.id = pa.participant_group_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND pa.advantage_type = $3
  AND pa.status = 'active'
  AND pa.effective_at <= $4
  AND (pa.effective_until IS NULL OR pa.effective_until > $4)
ORDER BY pa.granted_at ASC
`

type ListActiveAdvantagesByTypeForParticipantParams struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	AdvantageType string             `json:"advantage_type"`
	At            pgtype.Timestamptz `json:"at"`
}

type ListActiveAdvantagesByTypeForParticipantRow struct {
	ID                 pgtype.UUID        `json:"id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	AdvantageType      string             `json:"advantage_type"`
	Name               string             `json:"name"`
	Status             string             `json:"status"`
	GrantedAt          pgtype.Timestamptz `json:"granted_at"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	EffectiveUntil     pgtype.Timestamptz `json:"effective_until"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveAdvantagesByTypeForParticipant(ctx context.Context, arg ListActiveAdvantagesByTypeForParticipantParams) ([]ListActiveAdvantagesByTypeForParticipantRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdvantagesByTypeForParticipant,
		arg.InstanceID,
		arg.ParticipantID,
		arg.AdvantageType,
		arg.At,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdvantagesByTypeForParticipantRow{}
	for rows.Next() {
		var i ListActiveAdvantagesByTypeForParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ParticipantID,
			&i.ParticipantGroupID,
			&i.AdvantageType,
			&i.Name,
			&i.Status,
			&i.GrantedAt,
			&i.EffectiveAt,
			&i.EffectiveUntil,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAdvantageUsed = `-- name: MarkAdvantageUsed :exec
UPDATE participant_advantages
SET status = 'used', updated_at = NOW()
WHERE public_id = $1
  AND status = 'active'
`

func (q *Queries) MarkAdvantageUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAdvantageUsed, id)
	return err
}
