// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bonus_ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBonusPointLedgerEntry = `-- name: CreateBonusPointLedgerEntry :one
WITH resolved_instance AS (
    SELECT instances.id AS instance_internal_id, instances.public_id AS instance_id
    FROM instances
    WHERE instances.public_id = $8
), resolved_participant AS (
    SELECT p.id AS participant_internal_id, p.public_id AS participant_id
    FROM participants p
    JOIN resolved_instance ri ON ri.instance_internal_id = p.instance_id
    WHERE p.public_id = $9
), resolved_occurrence AS (
    SELECT ao.id AS activity_occurrence_internal_id, ao.public_id AS activity_occurrence_id
    FROM activity_occurrences ao
    JOIN instance_activities ia ON ia.id = ao.activity_id
    JOIN resolved_instance ri ON ri.instance_internal_id = ia.instance_id
    WHERE ao.public_id = $10
), resolved_source_group AS (
    SELECT pg.id AS source_group_internal_id, pg.public_id AS source_group_id
    FROM participant_groups pg
    JOIN resolved_instance ri ON ri.instance_internal_id = pg.instance_id
    WHERE pg.public_id = $11
)
INSERT INTO bonus_point_ledger_entries (
    instance_id,
    participant_id,
    activity_occurrence_id,
    source_group_id,
    entry_kind,
    points,
    visibility,
    reason,
    effective_at,
    award_key,
    metadata
)
SELECT
    ri.instance_internal_id,
    rp.participant_internal_id,
    ro.activity_occurrence_internal_id,
    rsg.source_group_internal_id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM resolved_instance ri
CROSS JOIN resolved_participant rp
CROSS JOIN resolved_occurrence ro
LEFT JOIN resolved_source_group rsg ON TRUE
RETURNING
    public_id AS id,
    (SELECT instance_id FROM resolved_instance) AS instance_id,
    (SELECT participant_id FROM resolved_participant) AS participant_id,
    (SELECT activity_occurrence_id FROM resolved_occurrence) AS activity_occurrence_id,
    (SELECT source_group_id FROM resolved_source_group) AS source_group_id,
    entry_kind,
    points,
    visibility,
    reason,
    effective_at,
    award_key,
    metadata,
    created_at
`

type CreateBonusPointLedgerEntryParams struct {
	EntryKind            string             `json:"entry_kind"`
	Points               int32              `json:"points"`
	Visibility           string             `json:"visibility"`
	Reason               string             `json:"reason"`
	EffectiveAt          pgtype.Timestamptz `json:"effective_at"`
	AwardKey             pgtype.Text        `json:"award_key"`
	Metadata             []byte             `json:"metadata"`
	InstanceID           pgtype.UUID        `json:"instance_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	SourceGroupID        pgtype.UUID        `json:"source_group_id"`
}

type CreateBonusPointLedgerEntryRow struct {
	ID                   pgtype.UUID        `json:"id"`
	InstanceID           pgtype.UUID        `json:"instance_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	SourceGroupID        pgtype.UUID        `json:"source_group_id"`
	EntryKind            string             `json:"entry_kind"`
	Points               int32              `json:"points"`
	Visibility           string             `json:"visibility"`
	Reason               string             `json:"reason"`
	EffectiveAt          pgtype.Timestamptz `json:"effective_at"`
	AwardKey             pgtype.Text        `json:"award_key"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateBonusPointLedgerEntry(ctx context.Context, arg CreateBonusPointLedgerEntryParams) (CreateBonusPointLedgerEntryRow, error) {
	row := q.db.QueryRow(ctx, createBonusPointLedgerEntry,
		arg.EntryKind,
		arg.Points,
		arg.Visibility,
		arg.Reason,
		arg.EffectiveAt,
		arg.AwardKey,
		arg.Metadata,
		arg.InstanceID,
		arg.ParticipantID,
		arg.ActivityOccurrenceID,
		arg.SourceGroupID,
	)
	var i CreateBonusPointLedgerEntryRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ParticipantID,
		&i.ActivityOccurrenceID,
		&i.SourceGroupID,
		&i.EntryKind,
		&i.Points,
		&i.Visibility,
		&i.Reason,
		&i.EffectiveAt,
		&i.AwardKey,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAvailableSecretBalanceByParticipant = `-- name: GetAvailableSecretBalanceByParticipant :one
SELECT GREATEST(COALESCE(SUM(bple.points), 0), 0)::INTEGER AS total_points
FROM bonus_point_ledger_entries bple
JOIN instances i ON i.id = bple.instance_id
JOIN participants p ON p.id = bple.participant_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND bple.visibility = 'secret'
`

type GetAvailableSecretBalanceByParticipantParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) GetAvailableSecretBalanceByParticipant(ctx context.Context, arg GetAvailableSecretBalanceByParticipantParams) (int32, error) {
	row := q.db.QueryRow(ctx, getAvailableSecretBalanceByParticipant, arg.InstanceID, arg.ParticipantID)
	var total_points int32
	err := row.Scan(&total_points)
	return total_points, err
}

const getSecretBonusTotalByParticipant = `-- name: GetSecretBonusTotalByParticipant :one
SELECT COALESCE(SUM(bple.points), 0)::INTEGER AS total_points
FROM bonus_point_ledger_entries bple
JOIN instances i ON i.id = bple.instance_id
JOIN participants p ON p.id = bple.participant_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND bple.visibility = 'secret'
`

type GetSecretBonusTotalByParticipantParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) GetSecretBonusTotalByParticipant(ctx context.Context, arg GetSecretBonusTotalByParticipantParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSecretBonusTotalByParticipant, arg.InstanceID, arg.ParticipantID)
	var total_points int32
	err := row.Scan(&total_points)
	return total_points, err
}

const getVisibleBonusTotalByParticipant = `-- name: GetVisibleBonusTotalByParticipant :one
SELECT COALESCE(SUM(bple.points), 0)::INTEGER AS total_points
FROM bonus_point_ledger_entries bple
JOIN instances i ON i.id = bple.instance_id
JOIN participants p ON p.id = bple.participant_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND bple.visibility IN ('public', 'revealed')
`

type GetVisibleBonusTotalByParticipantParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) GetVisibleBonusTotalByParticipant(ctx context.Context, arg GetVisibleBonusTotalByParticipantParams) (int32, error) {
	row := q.db.QueryRow(ctx, getVisibleBonusTotalByParticipant, arg.InstanceID, arg.ParticipantID)
	var total_points int32
	err := row.Scan(&total_points)
	return total_points, err
}

const getVisibleBonusTotalByParticipantAsOf = `-- name: GetVisibleBonusTotalByParticipantAsOf :one
SELECT COALESCE(SUM(bple.points), 0)::INTEGER AS total_points
FROM bonus_point_ledger_entries bple
JOIN instances i ON i.id = bple.instance_id
JOIN participants p ON p.id = bple.participant_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND bple.visibility IN ('public', 'revealed')
  AND bple.effective_at <= $3
`

type GetVisibleBonusTotalByParticipantAsOfParams struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	AsOf          pgtype.Timestamptz `json:"as_of"`
}

func (q *Queries) GetVisibleBonusTotalByParticipantAsOf(ctx context.Context, arg GetVisibleBonusTotalByParticipantAsOfParams) (int32, error) {
	row := q.db.QueryRow(ctx, getVisibleBonusTotalByParticipantAsOf, arg.InstanceID, arg.ParticipantID, arg.AsOf)
	var total_points int32
	err := row.Scan(&total_points)
	return total_points, err
}

const listAllBonusPointLedgerEntriesForParticipant = `-- name: ListAllBonusPointLedgerEntriesForParticipant :many
SELECT
    bple.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    ao.public_id AS activity_occurrence_id,
    ao.occurrence_type,
    ao.name AS occurrence_name,
    ia.public_id AS activity_id,
    ia.activity_type,
    ia.name AS activity_name,
    sg.public_id AS source_group_id,
    sg.name AS source_group_name,
    bple.entry_kind,
    bple.points,
    bple.visibility,
    bple.reason,
    bple.effective_at,
    bple.award_key,
    bple.metadata,
    bple.created_at
FROM bonus_point_ledger_entries bple
JOIN instances i ON i.id = bple.instance_id
JOIN participants p ON p.id = bple.participant_id
JOIN activity_occurrences ao ON ao.id = bple.activity_occurrence_id
JOIN instance_activities ia ON ia.id = ao.activity_id
LEFT JOIN participant_groups sg ON sg.id = bple.source_group_id
WHERE i.public_id = $1
  AND p.public_id = $2
ORDER BY bple.effective_at ASC, bple.created_at ASC, bple.id ASC
`

type ListAllBonusPointLedgerEntriesForParticipantParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

type ListAllBonusPointLedgerEntriesForParticipantRow struct {
	ID                   pgtype.UUID        `json:"id"`
	InstanceID           pgtype.UUID        `json:"instance_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	OccurrenceType       string             `json:"occurrence_type"`
	OccurrenceName       string             `json:"occurrence_name"`
	ActivityID           pgtype.UUID        `json:"activity_id"`
	ActivityType         string             `json:"activity_type"`
	ActivityName         string             `json:"activity_name"`
	SourceGroupID        pgtype.UUID        `json:"source_group_id"`
	SourceGroupName      pgtype.Text        `json:"source_group_name"`
	EntryKind            string             `json:"entry_kind"`
	Points               int32              `json:"points"`
	Visibility           string             `json:"visibility"`
	Reason               string             `json:"reason"`
	EffectiveAt          pgtype.Timestamptz `json:"effective_at"`
	AwardKey             pgtype.Text        `json:"award_key"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAllBonusPointLedgerEntriesForParticipant(ctx context.Context, arg ListAllBonusPointLedgerEntriesForParticipantParams) ([]ListAllBonusPointLedgerEntriesForParticipantRow, error) {
	rows, err := q.db.Query(ctx, listAllBonusPointLedgerEntriesForParticipant, arg.InstanceID, arg.ParticipantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBonusPointLedgerEntriesForParticipantRow{}
	for rows.Next() {
		var i ListAllBonusPointLedgerEntriesForParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ParticipantID,
			&i.ActivityOccurrenceID,
			&i.OccurrenceType,
			&i.OccurrenceName,
			&i.ActivityID,
			&i.ActivityType,
			&i.ActivityName,
			&i.SourceGroupID,
			&i.SourceGroupName,
			&i.EntryKind,
			&i.Points,
			&i.Visibility,
			&i.Reason,
			&i.EffectiveAt,
			&i.AwardKey,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleBonusPointLedgerEntriesForParticipant = `-- name: ListVisibleBonusPointLedgerEntriesForParticipant :many
SELECT
    bple.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    ao.public_id AS activity_occurrence_id,
    ao.occurrence_type,
    ao.name AS occurrence_name,
    ia.public_id AS activity_id,
    ia.activity_type,
    ia.name AS activity_name,
    sg.public_id AS source_group_id,
    sg.name AS source_group_name,
    bple.entry_kind,
    bple.points,
    bple.visibility,
    bple.reason,
    bple.effective_at,
    bple.award_key,
    bple.metadata,
    bple.created_at
FROM bonus_point_ledger_entries bple
JOIN instances i ON i.id = bple.instance_id
JOIN participants p ON p.id = bple.participant_id
JOIN activity_occurrences ao ON ao.id = bple.activity_occurrence_id
JOIN instance_activities ia ON ia.id = ao.activity_id
LEFT JOIN participant_groups sg ON sg.id = bple.source_group_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND bple.visibility IN ('public', 'revealed')
ORDER BY bple.effective_at ASC, bple.created_at ASC, bple.id ASC
`

type ListVisibleBonusPointLedgerEntriesForParticipantParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

type ListVisibleBonusPointLedgerEntriesForParticipantRow struct {
	ID                   pgtype.UUID        `json:"id"`
	InstanceID           pgtype.UUID        `json:"instance_id"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	OccurrenceType       string             `json:"occurrence_type"`
	OccurrenceName       string             `json:"occurrence_name"`
	ActivityID           pgtype.UUID        `json:"activity_id"`
	ActivityType         string             `json:"activity_type"`
	ActivityName         string             `json:"activity_name"`
	SourceGroupID        pgtype.UUID        `json:"source_group_id"`
	SourceGroupName      pgtype.Text        `json:"source_group_name"`
	EntryKind            string             `json:"entry_kind"`
	Points               int32              `json:"points"`
	Visibility           string             `json:"visibility"`
	Reason               string             `json:"reason"`
	EffectiveAt          pgtype.Timestamptz `json:"effective_at"`
	AwardKey             pgtype.Text        `json:"award_key"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListVisibleBonusPointLedgerEntriesForParticipant(ctx context.Context, arg ListVisibleBonusPointLedgerEntriesForParticipantParams) ([]ListVisibleBonusPointLedgerEntriesForParticipantRow, error) {
	rows, err := q.db.Query(ctx, listVisibleBonusPointLedgerEntriesForParticipant, arg.InstanceID, arg.ParticipantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleBonusPointLedgerEntriesForParticipantRow{}
	for rows.Next() {
		var i ListVisibleBonusPointLedgerEntriesForParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ParticipantID,
			&i.ActivityOccurrenceID,
			&i.OccurrenceType,
			&i.OccurrenceName,
			&i.ActivityID,
			&i.ActivityType,
			&i.ActivityName,
			&i.SourceGroupID,
			&i.SourceGroupName,
			&i.EntryKind,
			&i.Points,
			&i.Visibility,
			&i.Reason,
			&i.EffectiveAt,
			&i.AwardKey,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
