// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: castawordle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCastawordleGame = `-- name: CreateCastawordleGame :one
INSERT INTO castawordle_games (instance_id, name, answer, dictionary_version, opens_at, cutoff_at, episode_number)
SELECT i.id, $1, $2, $3, $4, $5, $6
FROM instances i WHERE i.public_id = $7
RETURNING public_id AS id, (SELECT public_id FROM instances WHERE id = instance_id) AS instance_id,
    name, answer, dictionary_version, opens_at, cutoff_at, episode_number
`

type CreateCastawordleGameParams struct {
	Name              string             `json:"name"`
	Answer            string             `json:"answer"`
	DictionaryVersion string             `json:"dictionary_version"`
	OpensAt           pgtype.Timestamptz `json:"opens_at"`
	CutoffAt          pgtype.Timestamptz `json:"cutoff_at"`
	EpisodeNumber     pgtype.Int4        `json:"episode_number"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
}

type CreateCastawordleGameRow struct {
	ID                pgtype.UUID        `json:"id"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
	Name              string             `json:"name"`
	Answer            string             `json:"answer"`
	DictionaryVersion string             `json:"dictionary_version"`
	OpensAt           pgtype.Timestamptz `json:"opens_at"`
	CutoffAt          pgtype.Timestamptz `json:"cutoff_at"`
	EpisodeNumber     pgtype.Int4        `json:"episode_number"`
}

func (q *Queries) CreateCastawordleGame(ctx context.Context, arg CreateCastawordleGameParams) (CreateCastawordleGameRow, error) {
	row := q.db.QueryRow(ctx, createCastawordleGame,
		arg.Name,
		arg.Answer,
		arg.DictionaryVersion,
		arg.OpensAt,
		arg.CutoffAt,
		arg.EpisodeNumber,
		arg.InstanceID,
	)
	var i CreateCastawordleGameRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.Answer,
		&i.DictionaryVersion,
		&i.OpensAt,
		&i.CutoffAt,
		&i.EpisodeNumber,
	)
	return i, err
}

const ensureCastawordlePlay = `-- name: EnsureCastawordlePlay :exec
INSERT INTO castawordle_plays (game_id, participant_id)
SELECT g.id, p.id FROM castawordle_games g
JOIN participants p ON p.instance_id = g.instance_id
WHERE g.public_id = $1 AND p.public_id = $2
ON CONFLICT (game_id, participant_id) DO NOTHING
`

type EnsureCastawordlePlayParams struct {
	GameID        pgtype.UUID `json:"game_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

func (q *Queries) EnsureCastawordlePlay(ctx context.Context, arg EnsureCastawordlePlayParams) error {
	_, err := q.db.Exec(ctx, ensureCastawordlePlay, arg.GameID, arg.ParticipantID)
	return err
}

const getCastawordleGame = `-- name: GetCastawordleGame :one
SELECT g.public_id AS id, i.public_id AS instance_id, g.name, g.answer, g.dictionary_version, g.opens_at, g.cutoff_at, g.episode_number
FROM castawordle_games g JOIN instances i ON i.id = g.instance_id
WHERE g.public_id = $1
`

type GetCastawordleGameRow struct {
	ID                pgtype.UUID        `json:"id"`
	InstanceID        pgtype.UUID        `json:"instance_id"`
	Name              string             `json:"name"`
	Answer            string             `json:"answer"`
	DictionaryVersion string             `json:"dictionary_version"`
	OpensAt           pgtype.Timestamptz `json:"opens_at"`
	CutoffAt          pgtype.Timestamptz `json:"cutoff_at"`
	EpisodeNumber     pgtype.Int4        `json:"episode_number"`
}

func (q *Queries) GetCastawordleGame(ctx context.Context, id pgtype.UUID) (GetCastawordleGameRow, error) {
	row := q.db.QueryRow(ctx, getCastawordleGame, id)
	var i GetCastawordleGameRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.Answer,
		&i.DictionaryVersion,
		&i.OpensAt,
		&i.CutoffAt,
		&i.EpisodeNumber,
	)
	return i, err
}

const getCastawordlePlay = `-- name: GetCastawordlePlay :one
SELECT guesses, status FROM castawordle_plays p
JOIN castawordle_games g ON g.id = p.game_id
JOIN participants player ON player.id = p.participant_id
WHERE g.public_id = $1 AND player.public_id = $2
`

type GetCastawordlePlayParams struct {
	GameID        pgtype.UUID `json:"game_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

type GetCastawordlePlayRow struct {
	Guesses []byte `json:"guesses"`
	Status  string `json:"status"`
}

func (q *Queries) GetCastawordlePlay(ctx context.Context, arg GetCastawordlePlayParams) (GetCastawordlePlayRow, error) {
	row := q.db.QueryRow(ctx, getCastawordlePlay, arg.GameID, arg.ParticipantID)
	var i GetCastawordlePlayRow
	err := row.Scan(&i.Guesses, &i.Status)
	return i, err
}

const listCastawordleGames = `-- name: ListCastawordleGames :many
SELECT g.public_id AS id, i.public_id AS instance_id, g.name, char_length(g.answer)::integer AS word_length,
    g.opens_at, g.cutoff_at, g.episode_number
FROM castawordle_games g JOIN instances i ON i.id = g.instance_id
WHERE i.public_id = $1
    AND (g.episode_number IS NOT NULL OR $2::boolean)
ORDER BY g.opens_at DESC, g.id DESC
`

type ListCastawordleGamesParams struct {
	InstanceID   pgtype.UUID `json:"instance_id"`
	IncludeTests bool        `json:"include_tests"`
}

type ListCastawordleGamesRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	Name          string             `json:"name"`
	WordLength    int32              `json:"word_length"`
	OpensAt       pgtype.Timestamptz `json:"opens_at"`
	CutoffAt      pgtype.Timestamptz `json:"cutoff_at"`
	EpisodeNumber pgtype.Int4        `json:"episode_number"`
}

func (q *Queries) ListCastawordleGames(ctx context.Context, arg ListCastawordleGamesParams) ([]ListCastawordleGamesRow, error) {
	rows, err := q.db.Query(ctx, listCastawordleGames, arg.InstanceID, arg.IncludeTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCastawordleGamesRow{}
	for rows.Next() {
		var i ListCastawordleGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.WordLength,
			&i.OpensAt,
			&i.CutoffAt,
			&i.EpisodeNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCastawordlePlay = `-- name: LockCastawordlePlay :one
SELECT guesses, status FROM castawordle_plays p
JOIN castawordle_games g ON g.id = p.game_id
JOIN participants player ON player.id = p.participant_id
WHERE g.public_id = $1 AND player.public_id = $2
FOR UPDATE OF p
`

type LockCastawordlePlayParams struct {
	GameID        pgtype.UUID `json:"game_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

type LockCastawordlePlayRow struct {
	Guesses []byte `json:"guesses"`
	Status  string `json:"status"`
}

func (q *Queries) LockCastawordlePlay(ctx context.Context, arg LockCastawordlePlayParams) (LockCastawordlePlayRow, error) {
	row := q.db.QueryRow(ctx, lockCastawordlePlay, arg.GameID, arg.ParticipantID)
	var i LockCastawordlePlayRow
	err := row.Scan(&i.Guesses, &i.Status)
	return i, err
}

const updateCastawordlePlay = `-- name: UpdateCastawordlePlay :exec
UPDATE castawordle_plays SET guesses = $1, status = $2, updated_at = $3
WHERE game_id = (SELECT g.id FROM castawordle_games g WHERE g.public_id = $4)
AND participant_id = (SELECT p.id FROM participants p WHERE p.public_id = $5)
`

type UpdateCastawordlePlayParams struct {
	Guesses       []byte             `json:"guesses"`
	Status        string             `json:"status"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	GameID        pgtype.UUID        `json:"game_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
}

func (q *Queries) UpdateCastawordlePlay(ctx context.Context, arg UpdateCastawordlePlayParams) error {
	_, err := q.db.Exec(ctx, updateCastawordlePlay,
		arg.Guesses,
		arg.Status,
		arg.UpdatedAt,
		arg.GameID,
		arg.ParticipantID,
	)
	return err
}
