// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contestants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContestant = `-- name: CreateContestant :one
WITH upserted AS (
    INSERT INTO contestants (name)
    VALUES ($1)
    ON CONFLICT (name)
    DO UPDATE SET name = EXCLUDED.name
    RETURNING id, public_id, name, created_at
), linked AS (
    INSERT INTO instance_contestants (instance_id, contestant_id)
    SELECT i.id, u.id
    FROM instances i
    CROSS JOIN upserted u
    WHERE i.public_id = $2
    ON CONFLICT (instance_id, contestant_id) DO NOTHING
)
SELECT public_id AS id, name, created_at
FROM upserted
`

type CreateContestantParams struct {
	Name       string      `json:"name"`
	InstanceID pgtype.UUID `json:"instance_id"`
}

type CreateContestantRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateContestant(ctx context.Context, arg CreateContestantParams) (CreateContestantRow, error) {
	row := q.db.QueryRow(ctx, createContestant, arg.Name, arg.InstanceID)
	var i CreateContestantRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getContestant = `-- name: GetContestant :one
SELECT public_id AS id, name, created_at
FROM contestants
WHERE public_id = $1
`

type GetContestantRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetContestant(ctx context.Context, id pgtype.UUID) (GetContestantRow, error) {
	row := q.db.QueryRow(ctx, getContestant, id)
	var i GetContestantRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const instanceHasContestant = `-- name: InstanceHasContestant :one
SELECT EXISTS (
    SELECT 1
    FROM instance_contestants ic
    JOIN instances i ON i.id = ic.instance_id
    JOIN contestants c ON c.id = ic.contestant_id
    WHERE i.public_id = $1
      AND c.public_id = $2
)
`

type InstanceHasContestantParams struct {
	InstanceID   pgtype.UUID `json:"instance_id"`
	ContestantID pgtype.UUID `json:"contestant_id"`
}

func (q *Queries) InstanceHasContestant(ctx context.Context, arg InstanceHasContestantParams) (bool, error) {
	row := q.db.QueryRow(ctx, instanceHasContestant, arg.InstanceID, arg.ContestantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listContestantsByInstance = `-- name: ListContestantsByInstance :many
SELECT c.public_id AS id, c.name, c.created_at
FROM contestants c
JOIN instance_contestants ic ON ic.contestant_id = c.id
JOIN instances i ON i.id = ic.instance_id
WHERE i.public_id = $1
ORDER BY c.name ASC
`

type ListContestantsByInstanceRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListContestantsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListContestantsByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listContestantsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestantsByInstanceRow{}
	for rows.Next() {
		var i ListContestantsByInstanceRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestantsGlobal = `-- name: ListContestantsGlobal :many
SELECT public_id AS id, name, created_at
FROM contestants
ORDER BY name ASC
`

type ListContestantsGlobalRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListContestantsGlobal(ctx context.Context) ([]ListContestantsGlobalRow, error) {
	rows, err := q.db.Query(ctx, listContestantsGlobal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestantsGlobalRow{}
	for rows.Next() {
		var i ListContestantsGlobalRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
