// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discord_channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDiscordChannelBinding = `-- name: DeleteDiscordChannelBinding :exec
DELETE FROM discord_channel_bindings WHERE guild_id = $1 AND channel_id = $2
`

type DeleteDiscordChannelBindingParams struct {
	GuildID   string `json:"guild_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) DeleteDiscordChannelBinding(ctx context.Context, arg DeleteDiscordChannelBindingParams) error {
	_, err := q.db.Exec(ctx, deleteDiscordChannelBinding, arg.GuildID, arg.ChannelID)
	return err
}

const getDiscordChannelBinding = `-- name: GetDiscordChannelBinding :one
SELECT b.guild_id, b.channel_id, i.public_id AS instance_id
FROM discord_channel_bindings b
JOIN instances i ON i.id = b.instance_id
WHERE b.guild_id = $1 AND b.channel_id = $2
`

type GetDiscordChannelBindingParams struct {
	GuildID   string `json:"guild_id"`
	ChannelID string `json:"channel_id"`
}

type GetDiscordChannelBindingRow struct {
	GuildID    string      `json:"guild_id"`
	ChannelID  string      `json:"channel_id"`
	InstanceID pgtype.UUID `json:"instance_id"`
}

func (q *Queries) GetDiscordChannelBinding(ctx context.Context, arg GetDiscordChannelBindingParams) (GetDiscordChannelBindingRow, error) {
	row := q.db.QueryRow(ctx, getDiscordChannelBinding, arg.GuildID, arg.ChannelID)
	var i GetDiscordChannelBindingRow
	err := row.Scan(&i.GuildID, &i.ChannelID, &i.InstanceID)
	return i, err
}

const lockDiscordChannel = `-- name: LockDiscordChannel :exec
SELECT pg_advisory_xact_lock(hashtextextended('discord-channel:' || $1::text, 0))
`

func (q *Queries) LockDiscordChannel(ctx context.Context, channelKey string) error {
	_, err := q.db.Exec(ctx, lockDiscordChannel, channelKey)
	return err
}

const setDiscordChannelBinding = `-- name: SetDiscordChannelBinding :exec
INSERT INTO discord_channel_bindings (guild_id, channel_id, instance_id)
SELECT $1, $2, i.id FROM instances i WHERE i.public_id = $3
ON CONFLICT (guild_id, channel_id) DO UPDATE SET instance_id = EXCLUDED.instance_id
`

type SetDiscordChannelBindingParams struct {
	GuildID    string      `json:"guild_id"`
	ChannelID  string      `json:"channel_id"`
	InstanceID pgtype.UUID `json:"instance_id"`
}

func (q *Queries) SetDiscordChannelBinding(ctx context.Context, arg SetDiscordChannelBindingParams) error {
	_, err := q.db.Exec(ctx, setDiscordChannelBinding, arg.GuildID, arg.ChannelID, arg.InstanceID)
	return err
}
