// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drafts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDraftPick = `-- name: CreateDraftPick :one
WITH resolved AS (
    SELECT
        i.id AS instance_internal_id,
        p.id AS participant_internal_id,
        c.id AS contestant_internal_id,
        i.public_id AS instance_id,
        p.public_id AS participant_id,
        c.public_id AS contestant_id
    FROM instances i
    JOIN participants p ON p.public_id = $2 AND p.instance_id = i.id
    JOIN contestants c ON c.public_id = $3
    JOIN instance_contestants ic ON ic.instance_id = i.id AND ic.contestant_id = c.id
    WHERE i.public_id = $4
)
INSERT INTO draft_picks (instance_id, participant_id, contestant_id, position)
SELECT instance_internal_id, participant_internal_id, contestant_internal_id, $1
FROM resolved
RETURNING
    (SELECT instance_id FROM resolved) AS instance_id,
    (SELECT participant_id FROM resolved) AS participant_id,
    (SELECT contestant_id FROM resolved) AS contestant_id,
    position,
    created_at
`

type CreateDraftPickParams struct {
	Position      int32       `json:"position"`
	ParticipantID pgtype.UUID `json:"participant_id"`
	ContestantID  pgtype.UUID `json:"contestant_id"`
	InstanceID    pgtype.UUID `json:"instance_id"`
}

type CreateDraftPickRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	ContestantID  pgtype.UUID        `json:"contestant_id"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDraftPick(ctx context.Context, arg CreateDraftPickParams) (CreateDraftPickRow, error) {
	row := q.db.QueryRow(ctx, createDraftPick,
		arg.Position,
		arg.ParticipantID,
		arg.ContestantID,
		arg.InstanceID,
	)
	var i CreateDraftPickRow
	err := row.Scan(
		&i.InstanceID,
		&i.ParticipantID,
		&i.ContestantID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDraftPicksForParticipant = `-- name: DeleteDraftPicksForParticipant :exec
DELETE FROM draft_picks dp
USING participants p
WHERE dp.participant_id = p.id
  AND p.public_id = $1
`

func (q *Queries) DeleteDraftPicksForParticipant(ctx context.Context, participantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraftPicksForParticipant, participantID)
	return err
}

const listDraftPicksForInstance = `-- name: ListDraftPicksForInstance :many
SELECT
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    c.public_id AS contestant_id,
    dp.position,
    dp.created_at
FROM draft_picks dp
JOIN instances i ON i.id = dp.instance_id
JOIN participants p ON p.id = dp.participant_id
JOIN contestants c ON c.id = dp.contestant_id
WHERE i.public_id = $1
ORDER BY p.public_id ASC, dp.position ASC
`

type ListDraftPicksForInstanceRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	ContestantID  pgtype.UUID        `json:"contestant_id"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDraftPicksForInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListDraftPicksForInstanceRow, error) {
	rows, err := q.db.Query(ctx, listDraftPicksForInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftPicksForInstanceRow{}
	for rows.Next() {
		var i ListDraftPicksForInstanceRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.ParticipantID,
			&i.ContestantID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftPicksForParticipant = `-- name: ListDraftPicksForParticipant :many
SELECT
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    c.public_id AS contestant_id,
    dp.position,
    dp.created_at
FROM draft_picks dp
JOIN instances i ON i.id = dp.instance_id
JOIN participants p ON p.id = dp.participant_id
JOIN contestants c ON c.id = dp.contestant_id
WHERE p.public_id = $1
ORDER BY dp.position ASC
`

type ListDraftPicksForParticipantRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	ContestantID  pgtype.UUID        `json:"contestant_id"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDraftPicksForParticipant(ctx context.Context, participantID pgtype.UUID) ([]ListDraftPicksForParticipantRow, error) {
	rows, err := q.db.Query(ctx, listDraftPicksForParticipant, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftPicksForParticipantRow{}
	for rows.Next() {
		var i ListDraftPicksForParticipantRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.ParticipantID,
			&i.ContestantID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
