// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: episodes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstanceEpisode = `-- name: CreateInstanceEpisode :one
INSERT INTO instance_episodes (instance_id, episode_number, label, airs_at, metadata)
SELECT i.id, $1, $2, $3, $4
FROM instances i
WHERE i.public_id = $5
RETURNING
    public_id AS id,
    (SELECT public_id FROM instances WHERE id = instance_episodes.instance_id) AS instance_id,
    episode_number,
    label,
    airs_at,
    metadata,
    created_at,
    updated_at
`

type CreateInstanceEpisodeParams struct {
	EpisodeNumber int32              `json:"episode_number"`
	Label         string             `json:"label"`
	AirsAt        pgtype.Timestamptz `json:"airs_at"`
	Metadata      []byte             `json:"metadata"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
}

type CreateInstanceEpisodeRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Label         string             `json:"label"`
	AirsAt        pgtype.Timestamptz `json:"airs_at"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateInstanceEpisode(ctx context.Context, arg CreateInstanceEpisodeParams) (CreateInstanceEpisodeRow, error) {
	row := q.db.QueryRow(ctx, createInstanceEpisode,
		arg.EpisodeNumber,
		arg.Label,
		arg.AirsAt,
		arg.Metadata,
		arg.InstanceID,
	)
	var i CreateInstanceEpisodeRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Label,
		&i.AirsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentEpisodeAt = `-- name: GetCurrentEpisodeAt :one
SELECT
    ie.public_id AS id,
    i.public_id AS instance_id,
    ie.episode_number,
    ie.label,
    ie.airs_at,
    ie.metadata,
    ie.created_at,
    ie.updated_at
FROM instance_episodes ie
JOIN instances i ON i.id = ie.instance_id
WHERE i.public_id = $1
  AND ie.airs_at <= $2
ORDER BY ie.airs_at DESC, ie.episode_number DESC
LIMIT 1
`

type GetCurrentEpisodeAtParams struct {
	InstanceID pgtype.UUID        `json:"instance_id"`
	At         pgtype.Timestamptz `json:"at"`
}

type GetCurrentEpisodeAtRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Label         string             `json:"label"`
	AirsAt        pgtype.Timestamptz `json:"airs_at"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCurrentEpisodeAt(ctx context.Context, arg GetCurrentEpisodeAtParams) (GetCurrentEpisodeAtRow, error) {
	row := q.db.QueryRow(ctx, getCurrentEpisodeAt, arg.InstanceID, arg.At)
	var i GetCurrentEpisodeAtRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Label,
		&i.AirsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEpisodeBoundaryWindows = `-- name: ListEpisodeBoundaryWindows :many
SELECT
    ie.episode_number,
    ie.label,
    ie.airs_at AS starts_at,
    LEAD(ie.airs_at) OVER (
        PARTITION BY ie.instance_id
        ORDER BY ie.airs_at ASC, ie.episode_number ASC
    ) AS ends_at
FROM instance_episodes ie
JOIN instances i ON i.id = ie.instance_id
WHERE i.public_id = $1
ORDER BY ie.episode_number ASC
`

type ListEpisodeBoundaryWindowsRow struct {
	EpisodeNumber int32              `json:"episode_number"`
	Label         string             `json:"label"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        interface{}        `json:"ends_at"`
}

func (q *Queries) ListEpisodeBoundaryWindows(ctx context.Context, instanceID pgtype.UUID) ([]ListEpisodeBoundaryWindowsRow, error) {
	rows, err := q.db.Query(ctx, listEpisodeBoundaryWindows, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpisodeBoundaryWindowsRow{}
	for rows.Next() {
		var i ListEpisodeBoundaryWindowsRow
		if err := rows.Scan(
			&i.EpisodeNumber,
			&i.Label,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstanceEpisodes = `-- name: ListInstanceEpisodes :many
SELECT
    ie.public_id AS id,
    i.public_id AS instance_id,
    ie.episode_number,
    ie.label,
    ie.airs_at,
    ie.metadata,
    ie.created_at,
    ie.updated_at
FROM instance_episodes ie
JOIN instances i ON i.id = ie.instance_id
WHERE i.public_id = $1
ORDER BY ie.episode_number ASC
`

type ListInstanceEpisodesRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Label         string             `json:"label"`
	AirsAt        pgtype.Timestamptz `json:"airs_at"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListInstanceEpisodes(ctx context.Context, instanceID pgtype.UUID) ([]ListInstanceEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listInstanceEpisodes, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstanceEpisodesRow{}
	for rows.Next() {
		var i ListInstanceEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.EpisodeNumber,
			&i.Label,
			&i.AirsAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
