// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipantGroup = `-- name: CreateParticipantGroup :one
INSERT INTO participant_groups (instance_id, name, kind, metadata)
SELECT i.id, $1, $2, $3
FROM instances i
WHERE i.public_id = $4
RETURNING
    public_id AS id,
    (SELECT public_id FROM instances WHERE id = participant_groups.instance_id) AS instance_id,
    name,
    kind,
    metadata,
    created_at,
    updated_at
`

type CreateParticipantGroupParams struct {
	Name       string      `json:"name"`
	Kind       string      `json:"kind"`
	Metadata   []byte      `json:"metadata"`
	InstanceID pgtype.UUID `json:"instance_id"`
}

type CreateParticipantGroupRow struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID pgtype.UUID        `json:"instance_id"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateParticipantGroup(ctx context.Context, arg CreateParticipantGroupParams) (CreateParticipantGroupRow, error) {
	row := q.db.QueryRow(ctx, createParticipantGroup,
		arg.Name,
		arg.Kind,
		arg.Metadata,
		arg.InstanceID,
	)
	var i CreateParticipantGroupRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.Kind,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createParticipantGroupMembershipPeriod = `-- name: CreateParticipantGroupMembershipPeriod :one
WITH resolved AS (
    SELECT
        pg.id AS participant_group_internal_id,
        p.id AS participant_internal_id,
        pg.public_id AS participant_group_id,
        p.public_id AS participant_id
    FROM participant_groups pg
    JOIN participants p ON p.public_id = $5
       AND p.instance_id = pg.instance_id
    WHERE pg.public_id = $6
)
INSERT INTO participant_group_membership_periods (
    participant_group_id,
    participant_id,
    role,
    starts_at,
    ends_at,
    metadata
)
SELECT
    participant_group_internal_id,
    participant_internal_id,
    $1,
    $2,
    $3,
    $4
FROM resolved
RETURNING
    id,
    (SELECT participant_group_id FROM resolved) AS participant_group_id,
    (SELECT participant_id FROM resolved) AS participant_id,
    role,
    starts_at,
    ends_at,
    metadata,
    created_at
`

type CreateParticipantGroupMembershipPeriodParams struct {
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Metadata           []byte             `json:"metadata"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
}

type CreateParticipantGroupMembershipPeriodRow struct {
	ID                 int64              `json:"id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateParticipantGroupMembershipPeriod(ctx context.Context, arg CreateParticipantGroupMembershipPeriodParams) (CreateParticipantGroupMembershipPeriodRow, error) {
	row := q.db.QueryRow(ctx, createParticipantGroupMembershipPeriod,
		arg.Role,
		arg.StartsAt,
		arg.EndsAt,
		arg.Metadata,
		arg.ParticipantID,
		arg.ParticipantGroupID,
	)
	var i CreateParticipantGroupMembershipPeriodRow
	err := row.Scan(
		&i.ID,
		&i.ParticipantGroupID,
		&i.ParticipantID,
		&i.Role,
		&i.StartsAt,
		&i.EndsAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantGroup = `-- name: GetParticipantGroup :one
SELECT
    pg.public_id AS id,
    i.public_id AS instance_id,
    pg.name,
    pg.kind,
    pg.metadata,
    pg.created_at,
    pg.updated_at
FROM participant_groups pg
JOIN instances i ON i.id = pg.instance_id
WHERE pg.public_id = $1
`

type GetParticipantGroupRow struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID pgtype.UUID        `json:"instance_id"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetParticipantGroup(ctx context.Context, id pgtype.UUID) (GetParticipantGroupRow, error) {
	row := q.db.QueryRow(ctx, getParticipantGroup, id)
	var i GetParticipantGroupRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.Kind,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveParticipantGroupMembershipsAt = `-- name: ListActiveParticipantGroupMembershipsAt :many
SELECT
    pgmp.id,
    pg.public_id AS participant_group_id,
    p.public_id AS participant_id,
    p.name AS participant_name,
    pgmp.role,
    pgmp.starts_at,
    pgmp.ends_at,
    pgmp.metadata,
    pgmp.created_at
FROM participant_group_membership_periods pgmp
JOIN participant_groups pg ON pg.id = pgmp.participant_group_id
JOIN participants p ON p.id = pgmp.participant_id
WHERE pg.public_id = $1
  AND pgmp.starts_at <= $2
  AND (pgmp.ends_at IS NULL OR pgmp.ends_at > $2)
ORDER BY p.name ASC, pgmp.id ASC
`

type ListActiveParticipantGroupMembershipsAtParams struct {
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	At                 pgtype.Timestamptz `json:"at"`
}

type ListActiveParticipantGroupMembershipsAtRow struct {
	ID                 int64              `json:"id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	ParticipantName    string             `json:"participant_name"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveParticipantGroupMembershipsAt(ctx context.Context, arg ListActiveParticipantGroupMembershipsAtParams) ([]ListActiveParticipantGroupMembershipsAtRow, error) {
	rows, err := q.db.Query(ctx, listActiveParticipantGroupMembershipsAt, arg.ParticipantGroupID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveParticipantGroupMembershipsAtRow{}
	for rows.Next() {
		var i ListActiveParticipantGroupMembershipsAtRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantGroupID,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.Role,
			&i.StartsAt,
			&i.EndsAt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveParticipantMembershipsAt = `-- name: ListActiveParticipantMembershipsAt :many
SELECT
    pgmp.id,
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    pg.kind AS participant_group_kind,
    p.public_id AS participant_id,
    p.name AS participant_name,
    pgmp.role,
    pgmp.starts_at,
    pgmp.ends_at,
    pgmp.metadata,
    pgmp.created_at
FROM participant_group_membership_periods pgmp
JOIN participant_groups pg ON pg.id = pgmp.participant_group_id
JOIN participants p ON p.id = pgmp.participant_id
WHERE p.public_id = $1
  AND pgmp.starts_at <= $2
  AND (pgmp.ends_at IS NULL OR pgmp.ends_at > $2)
ORDER BY pg.kind ASC, pg.name ASC, pgmp.id ASC
`

type ListActiveParticipantMembershipsAtParams struct {
	ParticipantID pgtype.UUID        `json:"participant_id"`
	At            pgtype.Timestamptz `json:"at"`
}

type ListActiveParticipantMembershipsAtRow struct {
	ID                   int64              `json:"id"`
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName string             `json:"participant_group_name"`
	ParticipantGroupKind string             `json:"participant_group_kind"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantName      string             `json:"participant_name"`
	Role                 string             `json:"role"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveParticipantMembershipsAt(ctx context.Context, arg ListActiveParticipantMembershipsAtParams) ([]ListActiveParticipantMembershipsAtRow, error) {
	rows, err := q.db.Query(ctx, listActiveParticipantMembershipsAt, arg.ParticipantID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveParticipantMembershipsAtRow{}
	for rows.Next() {
		var i ListActiveParticipantMembershipsAtRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.ParticipantGroupKind,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.Role,
			&i.StartsAt,
			&i.EndsAt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantGroupMembershipPeriods = `-- name: ListParticipantGroupMembershipPeriods :many
SELECT
    pgmp.id,
    pg.public_id AS participant_group_id,
    p.public_id AS participant_id,
    pgmp.role,
    pgmp.starts_at,
    pgmp.ends_at,
    pgmp.metadata,
    pgmp.created_at
FROM participant_group_membership_periods pgmp
JOIN participant_groups pg ON pg.id = pgmp.participant_group_id
JOIN participants p ON p.id = pgmp.participant_id
WHERE pg.public_id = $1
ORDER BY pgmp.starts_at ASC, pgmp.id ASC
`

type ListParticipantGroupMembershipPeriodsRow struct {
	ID                 int64              `json:"id"`
	ParticipantGroupID pgtype.UUID        `json:"participant_group_id"`
	ParticipantID      pgtype.UUID        `json:"participant_id"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListParticipantGroupMembershipPeriods(ctx context.Context, participantGroupID pgtype.UUID) ([]ListParticipantGroupMembershipPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listParticipantGroupMembershipPeriods, participantGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantGroupMembershipPeriodsRow{}
	for rows.Next() {
		var i ListParticipantGroupMembershipPeriodsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantGroupID,
			&i.ParticipantID,
			&i.Role,
			&i.StartsAt,
			&i.EndsAt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantGroupsByInstance = `-- name: ListParticipantGroupsByInstance :many
SELECT
    pg.public_id AS id,
    i.public_id AS instance_id,
    pg.name,
    pg.kind,
    pg.metadata,
    pg.created_at,
    pg.updated_at
FROM participant_groups pg
JOIN instances i ON i.id = pg.instance_id
WHERE i.public_id = $1
ORDER BY pg.kind ASC, pg.name ASC
`

type ListParticipantGroupsByInstanceRow struct {
	ID         pgtype.UUID        `json:"id"`
	InstanceID pgtype.UUID        `json:"instance_id"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListParticipantGroupsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListParticipantGroupsByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listParticipantGroupsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantGroupsByInstanceRow{}
	for rows.Next() {
		var i ListParticipantGroupsByInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.Kind,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
