// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_admins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInstanceAdmins = `-- name: CountInstanceAdmins :one
SELECT COUNT(*)::bigint
FROM instance_admins ia
JOIN instances i ON i.id = ia.instance_id
WHERE i.public_id = $1
`

func (q *Queries) CountInstanceAdmins(ctx context.Context, instanceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInstanceAdmins, instanceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInstanceAdmin = `-- name: CreateInstanceAdmin :one
INSERT INTO instance_admins (instance_id, discord_user_id)
SELECT i.id, $1
FROM instances i
WHERE i.public_id = $2
RETURNING
    id,
    instance_id,
    discord_user_id,
    created_at
`

type CreateInstanceAdminParams struct {
	DiscordUserID string      `json:"discord_user_id"`
	InstanceID    pgtype.UUID `json:"instance_id"`
}

func (q *Queries) CreateInstanceAdmin(ctx context.Context, arg CreateInstanceAdminParams) (InstanceAdmin, error) {
	row := q.db.QueryRow(ctx, createInstanceAdmin, arg.DiscordUserID, arg.InstanceID)
	var i InstanceAdmin
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInstanceAdmin = `-- name: DeleteInstanceAdmin :exec
DELETE FROM instance_admins ia
USING instances i
WHERE ia.instance_id = i.id
  AND i.public_id = $1
  AND ia.discord_user_id = $2
`

type DeleteInstanceAdminParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	DiscordUserID string      `json:"discord_user_id"`
}

func (q *Queries) DeleteInstanceAdmin(ctx context.Context, arg DeleteInstanceAdminParams) error {
	_, err := q.db.Exec(ctx, deleteInstanceAdmin, arg.InstanceID, arg.DiscordUserID)
	return err
}

const isInstanceAdmin = `-- name: IsInstanceAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM instance_admins ia
    JOIN instances i ON i.id = ia.instance_id
    WHERE i.public_id = $1
      AND ia.discord_user_id = $2
)
`

type IsInstanceAdminParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	DiscordUserID string      `json:"discord_user_id"`
}

func (q *Queries) IsInstanceAdmin(ctx context.Context, arg IsInstanceAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isInstanceAdmin, arg.InstanceID, arg.DiscordUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listInstanceAdmins = `-- name: ListInstanceAdmins :many
SELECT
    ia.id,
    i.public_id AS instance_id,
    ia.discord_user_id,
    ia.created_at
FROM instance_admins ia
JOIN instances i ON i.id = ia.instance_id
WHERE i.public_id = $1
ORDER BY ia.created_at ASC
`

type ListInstanceAdminsRow struct {
	ID            int64              `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	DiscordUserID string             `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListInstanceAdmins(ctx context.Context, instanceID pgtype.UUID) ([]ListInstanceAdminsRow, error) {
	rows, err := q.db.Query(ctx, listInstanceAdmins, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstanceAdminsRow{}
	for rows.Next() {
		var i ListInstanceAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.DiscordUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
