// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (name, season)
VALUES ($1, $2)
RETURNING public_id AS id, name, season, created_at
`

type CreateInstanceParams struct {
	Name   string `json:"name"`
	Season int32  `json:"season"`
}

type CreateInstanceRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Season    int32              `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (CreateInstanceRow, error) {
	row := q.db.QueryRow(ctx, createInstance, arg.Name, arg.Season)
	var i CreateInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Season,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInstanceByNameSeason = `-- name: DeleteInstanceByNameSeason :exec
DELETE FROM instances
WHERE name = $1 AND season = $2
`

type DeleteInstanceByNameSeasonParams struct {
	Name   string `json:"name"`
	Season int32  `json:"season"`
}

func (q *Queries) DeleteInstanceByNameSeason(ctx context.Context, arg DeleteInstanceByNameSeasonParams) error {
	_, err := q.db.Exec(ctx, deleteInstanceByNameSeason, arg.Name, arg.Season)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT public_id AS id, name, season, created_at
FROM instances
WHERE public_id = $1
`

type GetInstanceRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Season    int32              `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetInstance(ctx context.Context, id pgtype.UUID) (GetInstanceRow, error) {
	row := q.db.QueryRow(ctx, getInstance, id)
	var i GetInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Season,
		&i.CreatedAt,
	)
	return i, err
}

const listInstances = `-- name: ListInstances :many
SELECT public_id AS id, name, season, created_at
FROM instances
ORDER BY created_at DESC
`

type ListInstancesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Season    int32              `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListInstances(ctx context.Context) ([]ListInstancesRow, error) {
	rows, err := q.db.Query(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstancesRow{}
	for rows.Next() {
		var i ListInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Season,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstanceName = `-- name: UpdateInstanceName :one
UPDATE instances
SET name = $2
WHERE public_id = $1
RETURNING public_id AS id, name, season, created_at
`

type UpdateInstanceNameParams struct {
	PublicID pgtype.UUID `json:"public_id"`
	Name     string      `json:"name"`
}

type UpdateInstanceNameRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Season    int32              `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateInstanceName(ctx context.Context, arg UpdateInstanceNameParams) (UpdateInstanceNameRow, error) {
	row := q.db.QueryRow(ctx, updateInstanceName, arg.PublicID, arg.Name)
	var i UpdateInstanceNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Season,
		&i.CreatedAt,
	)
	return i, err
}
