// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contestant struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DraftPick struct {
	InstanceID    int64              `json:"instance_id"`
	ParticipantID int64              `json:"participant_id"`
	ContestantID  int64              `json:"contestant_id"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Instance struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Name      string             `json:"name"`
	Season    int32              `json:"season"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type InstanceContestant struct {
	InstanceID   int64              `json:"instance_id"`
	ContestantID int64              `json:"contestant_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type OutcomePosition struct {
	InstanceID   int64              `json:"instance_id"`
	Position     int32              `json:"position"`
	ContestantID pgtype.Int8        `json:"contestant_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Participant struct {
	ID         int64              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	InstanceID int64              `json:"instance_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
