// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityGroupAssignment struct {
	ID                 int64              `json:"id"`
	ActivityID         int64              `json:"activity_id"`
	ParticipantGroupID int64              `json:"participant_group_id"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Configuration      []byte             `json:"configuration"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ActivityOccurrence struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	ActivityID     int64              `json:"activity_id"`
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	Status         string             `json:"status"`
	SourceRef      pgtype.Text        `json:"source_ref"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ActivityOccurrenceGroup struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID int64              `json:"activity_occurrence_id"`
	ParticipantGroupID   int64              `json:"participant_group_id"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ActivityOccurrenceParticipant struct {
	ID                   int64              `json:"id"`
	ActivityOccurrenceID int64              `json:"activity_occurrence_id"`
	ParticipantID        int64              `json:"participant_id"`
	ParticipantGroupID   pgtype.Int8        `json:"participant_group_id"`
	Role                 string             `json:"role"`
	Result               string             `json:"result"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type ActivityParticipantAssignment struct {
	ID                 int64              `json:"id"`
	ActivityID         int64              `json:"activity_id"`
	ParticipantID      int64              `json:"participant_id"`
	ParticipantGroupID pgtype.Int8        `json:"participant_group_id"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Configuration      []byte             `json:"configuration"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Announcement struct {
	ID          pgtype.UUID        `json:"id"`
	InstanceID  int64              `json:"instance_id"`
	GuildID     string             `json:"guild_id"`
	ChannelID   string             `json:"channel_id"`
	RequestKey  string             `json:"request_key"`
	Body        string             `json:"body"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	Status      string             `json:"status"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	MessageID   pgtype.Text        `json:"message_id"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BonusPointLedgerEntry struct {
	ID                   int64              `json:"id"`
	PublicID             pgtype.UUID        `json:"public_id"`
	InstanceID           int64              `json:"instance_id"`
	ParticipantID        int64              `json:"participant_id"`
	ActivityOccurrenceID int64              `json:"activity_occurrence_id"`
	SourceGroupID        pgtype.Int8        `json:"source_group_id"`
	EntryKind            string             `json:"entry_kind"`
	Points               int32              `json:"points"`
	Visibility           string             `json:"visibility"`
	Reason               string             `json:"reason"`
	EffectiveAt          pgtype.Timestamptz `json:"effective_at"`
	AwardKey             pgtype.Text        `json:"award_key"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Contestant struct {
	ID        int64              `json:"id"`
	PublicID  pgtype.UUID        `json:"public_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DiscordChannelBinding struct {
	GuildID    string `json:"guild_id"`
	ChannelID  string `json:"channel_id"`
	InstanceID int64  `json:"instance_id"`
}

type DraftPick struct {
	InstanceID    int64              `json:"instance_id"`
	ParticipantID int64              `json:"participant_id"`
	ContestantID  int64              `json:"contestant_id"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Import struct {
	ID               int64              `json:"id"`
	PublicID         pgtype.UUID        `json:"public_id"`
	InstanceID       pgtype.Int8        `json:"instance_id"`
	Name             string             `json:"name"`
	Season           int32              `json:"season"`
	ContentType      string             `json:"content_type"`
	Payload          string             `json:"payload"`
	Status           string             `json:"status"`
	Error            pgtype.Text        `json:"error"`
	SubmissionsCount int32              `json:"submissions_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Instance struct {
	ID              int64              `json:"id"`
	PublicID        pgtype.UUID        `json:"public_id"`
	Name            string             `json:"name"`
	Season          int32              `json:"season"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProgressionMode string             `json:"progression_mode"`
}

type InstanceActivity struct {
	ID           int64              `json:"id"`
	PublicID     pgtype.UUID        `json:"public_id"`
	InstanceID   int64              `json:"instance_id"`
	ActivityType string             `json:"activity_type"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type InstanceAdmin struct {
	ID            int64              `json:"id"`
	InstanceID    int64              `json:"instance_id"`
	DiscordUserID string             `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type InstanceContestant struct {
	InstanceID   int64              `json:"instance_id"`
	ContestantID int64              `json:"contestant_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type InstanceDraftProgress struct {
	InstanceID int64              `json:"instance_id"`
	Status     string             `json:"status"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type InstanceEpisode struct {
	ID            int64              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	InstanceID    int64              `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Label         string             `json:"label"`
	AirsAt        pgtype.Timestamptz `json:"airs_at"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type InstanceEpisodeProgress struct {
	InstanceID    int64              `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ScoredAt      pgtype.Timestamptz `json:"scored_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type InstanceProgressionCommand struct {
	ID                 int64              `json:"id"`
	InstanceID         int64              `json:"instance_id"`
	CommandKey         string             `json:"command_key"`
	Operation          string             `json:"operation"`
	ActorDiscordUserID string             `json:"actor_discord_user_id"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	PayloadHash        string             `json:"payload_hash"`
	Payload            []byte             `json:"payload"`
	Response           []byte             `json:"response"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type InstanceScoreRevision struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	InstanceID     int64              `json:"instance_id"`
	RevisionNumber int32              `json:"revision_number"`
	EpisodeNumber  int32              `json:"episode_number"`
	Reason         string             `json:"reason"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	InputSnapshot  []byte             `json:"input_snapshot"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type InstanceScoreRevisionRow struct {
	RevisionID      int64  `json:"revision_id"`
	ParticipantID   int64  `json:"participant_id"`
	ParticipantName string `json:"participant_name"`
	Score           int32  `json:"score"`
	DraftPoints     int32  `json:"draft_points"`
	BonusPoints     int32  `json:"bonus_points"`
	TotalPoints     int32  `json:"total_points"`
	PointsAvailable int32  `json:"points_available"`
}

type OutcomePosition struct {
	InstanceID   int64              `json:"instance_id"`
	Position     int32              `json:"position"`
	ContestantID pgtype.Int8        `json:"contestant_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Participant struct {
	ID            int64              `json:"id"`
	PublicID      pgtype.UUID        `json:"public_id"`
	InstanceID    int64              `json:"instance_id"`
	Name          string             `json:"name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DiscordUserID pgtype.Text        `json:"discord_user_id"`
}

type ParticipantAdvantage struct {
	ID                         int64              `json:"id"`
	PublicID                   pgtype.UUID        `json:"public_id"`
	InstanceID                 int64              `json:"instance_id"`
	ParticipantID              int64              `json:"participant_id"`
	ParticipantGroupID         pgtype.Int8        `json:"participant_group_id"`
	AdvantageType              string             `json:"advantage_type"`
	Name                       string             `json:"name"`
	Status                     string             `json:"status"`
	SourceActivityOccurrenceID pgtype.Int8        `json:"source_activity_occurrence_id"`
	GrantedAt                  pgtype.Timestamptz `json:"granted_at"`
	EffectiveAt                pgtype.Timestamptz `json:"effective_at"`
	EffectiveUntil             pgtype.Timestamptz `json:"effective_until"`
	Metadata                   []byte             `json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type ParticipantGroup struct {
	ID         int64              `json:"id"`
	PublicID   pgtype.UUID        `json:"public_id"`
	InstanceID int64              `json:"instance_id"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ParticipantGroupMembershipPeriod struct {
	ID                 int64              `json:"id"`
	ParticipantGroupID int64              `json:"participant_group_id"`
	ParticipantID      int64              `json:"participant_id"`
	Role               string             `json:"role"`
	StartsAt           pgtype.Timestamptz `json:"starts_at"`
	EndsAt             pgtype.Timestamptz `json:"ends_at"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ParticipantLoan struct {
	ID                    int64              `json:"id"`
	PublicID              pgtype.UUID        `json:"public_id"`
	InstanceID            int64              `json:"instance_id"`
	ParticipantID         int64              `json:"participant_id"`
	ActivityID            pgtype.Int8        `json:"activity_id"`
	Status                string             `json:"status"`
	PrincipalPoints       int32              `json:"principal_points"`
	InterestPoints        int32              `json:"interest_points"`
	PrincipalRepaidPoints int32              `json:"principal_repaid_points"`
	InterestRepaidPoints  int32              `json:"interest_repaid_points"`
	GrantedAt             pgtype.Timestamptz `json:"granted_at"`
	DueAt                 pgtype.Timestamptz `json:"due_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ParticipantPonyOwnership struct {
	ID                         int64              `json:"id"`
	PublicID                   pgtype.UUID        `json:"public_id"`
	InstanceID                 int64              `json:"instance_id"`
	OwnerParticipantID         int64              `json:"owner_participant_id"`
	ContestantID               int64              `json:"contestant_id"`
	SourceActivityOccurrenceID pgtype.Int8        `json:"source_activity_occurrence_id"`
	AcquiredAt                 pgtype.Timestamptz `json:"acquired_at"`
	ReleasedAt                 pgtype.Timestamptz `json:"released_at"`
	Status                     string             `json:"status"`
	Metadata                   []byte             `json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type WordleRound struct {
	ID                   int64              `json:"id"`
	ActivityID           int64              `json:"activity_id"`
	ActivityOccurrenceID int64              `json:"activity_occurrence_id"`
	RoundKey             string             `json:"round_key"`
	OpensAt              pgtype.Timestamptz `json:"opens_at"`
	CutoffAt             pgtype.Timestamptz `json:"cutoff_at"`
	ClosedAt             pgtype.Timestamptz `json:"closed_at"`
	ResolutionResponse   []byte             `json:"resolution_response"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
