// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outcomes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOutcomePositionsByInstance = `-- name: ListOutcomePositionsByInstance :many
SELECT
    i.public_id AS instance_id,
    op.position,
    c.public_id AS contestant_id,
    op.updated_at
FROM outcome_positions op
JOIN instances i ON i.id = op.instance_id
LEFT JOIN contestants c ON c.id = op.contestant_id
WHERE i.public_id = $1
ORDER BY op.position ASC
`

type ListOutcomePositionsByInstanceRow struct {
	InstanceID   pgtype.UUID        `json:"instance_id"`
	Position     int32              `json:"position"`
	ContestantID pgtype.UUID        `json:"contestant_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListOutcomePositionsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListOutcomePositionsByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listOutcomePositionsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutcomePositionsByInstanceRow{}
	for rows.Next() {
		var i ListOutcomePositionsByInstanceRow
		if err := rows.Scan(
			&i.InstanceID,
			&i.Position,
			&i.ContestantID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOutcomePosition = `-- name: UpsertOutcomePosition :one
WITH resolved_instance AS (
    SELECT id AS instance_internal_id, public_id AS instance_id
    FROM instances
    WHERE instances.public_id = $1
), resolved_contestant AS (
    SELECT c.id AS contestant_internal_id, c.public_id AS contestant_id
    FROM contestants c
    JOIN instance_contestants ic ON ic.contestant_id = c.id
    JOIN resolved_instance ri ON ri.instance_internal_id = ic.instance_id
    WHERE c.public_id = $2
), upserted AS (
    INSERT INTO outcome_positions (instance_id, position, contestant_id, updated_at)
    VALUES (
        (SELECT instance_internal_id FROM resolved_instance),
        $3,
        (SELECT contestant_internal_id FROM resolved_contestant),
        NOW()
    )
    ON CONFLICT (instance_id, position)
    DO UPDATE SET contestant_id = EXCLUDED.contestant_id, updated_at = NOW()
    RETURNING instance_id, position, contestant_id, updated_at
)
SELECT
    (SELECT instance_id FROM resolved_instance) AS instance_id,
    upserted.position,
    (SELECT contestant_id FROM resolved_contestant) AS contestant_id,
    upserted.updated_at
FROM upserted
`

type UpsertOutcomePositionParams struct {
	InstanceID   pgtype.UUID `json:"instance_id"`
	ContestantID pgtype.UUID `json:"contestant_id"`
	Position     int32       `json:"position"`
}

type UpsertOutcomePositionRow struct {
	InstanceID   pgtype.UUID        `json:"instance_id"`
	Position     int32              `json:"position"`
	ContestantID pgtype.UUID        `json:"contestant_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertOutcomePosition(ctx context.Context, arg UpsertOutcomePositionParams) (UpsertOutcomePositionRow, error) {
	row := q.db.QueryRow(ctx, upsertOutcomePosition, arg.InstanceID, arg.ContestantID, arg.Position)
	var i UpsertOutcomePositionRow
	err := row.Scan(
		&i.InstanceID,
		&i.Position,
		&i.ContestantID,
		&i.UpdatedAt,
	)
	return i, err
}
