// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearParticipantDiscordUserID = `-- name: ClearParticipantDiscordUserID :one
UPDATE participants p
SET discord_user_id = NULL
WHERE p.public_id = $1
RETURNING
    p.public_id AS id,
    (SELECT public_id FROM instances WHERE id = p.instance_id) AS instance_id,
    p.name,
    p.discord_user_id,
    p.created_at
`

type ClearParticipantDiscordUserIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	Name          string             `json:"name"`
	DiscordUserID pgtype.Text        `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClearParticipantDiscordUserID(ctx context.Context, id pgtype.UUID) (ClearParticipantDiscordUserIDRow, error) {
	row := q.db.QueryRow(ctx, clearParticipantDiscordUserID, id)
	var i ClearParticipantDiscordUserIDRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (instance_id, name)
SELECT i.id, $1
FROM instances i
WHERE i.public_id = $2
RETURNING
    public_id AS id,
    (SELECT public_id FROM instances WHERE id = participants.instance_id) AS instance_id,
    name,
    discord_user_id,
    created_at
`

type CreateParticipantParams struct {
	Name       string      `json:"name"`
	InstanceID pgtype.UUID `json:"instance_id"`
}

type CreateParticipantRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	Name          string             `json:"name"`
	DiscordUserID pgtype.Text        `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (CreateParticipantRow, error) {
	row := q.db.QueryRow(ctx, createParticipant, arg.Name, arg.InstanceID)
	var i CreateParticipantRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT
    p.public_id AS id,
    i.public_id AS instance_id,
    p.name,
    p.discord_user_id,
    p.created_at
FROM participants p
JOIN instances i ON i.id = p.instance_id
WHERE p.public_id = $1
`

type GetParticipantRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	Name          string             `json:"name"`
	DiscordUserID pgtype.Text        `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetParticipant(ctx context.Context, id pgtype.UUID) (GetParticipantRow, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i GetParticipantRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByDiscordUserID = `-- name: GetParticipantByDiscordUserID :one
SELECT
    p.public_id AS id,
    i.public_id AS instance_id,
    p.name,
    p.discord_user_id,
    p.created_at
FROM participants p
JOIN instances i ON i.id = p.instance_id
WHERE i.public_id = $1
  AND p.discord_user_id = $2
`

type GetParticipantByDiscordUserIDParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	DiscordUserID pgtype.Text `json:"discord_user_id"`
}

type GetParticipantByDiscordUserIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	Name          string             `json:"name"`
	DiscordUserID pgtype.Text        `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetParticipantByDiscordUserID(ctx context.Context, arg GetParticipantByDiscordUserIDParams) (GetParticipantByDiscordUserIDRow, error) {
	row := q.db.QueryRow(ctx, getParticipantByDiscordUserID, arg.InstanceID, arg.DiscordUserID)
	var i GetParticipantByDiscordUserIDRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listParticipantsByInstance = `-- name: ListParticipantsByInstance :many
SELECT
    p.public_id AS id,
    i.public_id AS instance_id,
    p.name,
    p.discord_user_id,
    p.created_at
FROM participants p
JOIN instances i ON i.id = p.instance_id
WHERE i.public_id = $1
ORDER BY p.created_at ASC
`

type ListParticipantsByInstanceRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	Name          string             `json:"name"`
	DiscordUserID pgtype.Text        `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListParticipantsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListParticipantsByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParticipantsByInstanceRow{}
	for rows.Next() {
		var i ListParticipantsByInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Name,
			&i.DiscordUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setParticipantDiscordUserID = `-- name: SetParticipantDiscordUserID :one
UPDATE participants p
SET discord_user_id = $1
WHERE p.public_id = $2
RETURNING
    p.public_id AS id,
    (SELECT public_id FROM instances WHERE id = p.instance_id) AS instance_id,
    p.name,
    p.discord_user_id,
    p.created_at
`

type SetParticipantDiscordUserIDParams struct {
	DiscordUserID pgtype.Text `json:"discord_user_id"`
	ID            pgtype.UUID `json:"id"`
}

type SetParticipantDiscordUserIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	Name          string             `json:"name"`
	DiscordUserID pgtype.Text        `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SetParticipantDiscordUserID(ctx context.Context, arg SetParticipantDiscordUserIDParams) (SetParticipantDiscordUserIDRow, error) {
	row := q.db.QueryRow(ctx, setParticipantDiscordUserID, arg.DiscordUserID, arg.ID)
	var i SetParticipantDiscordUserIDRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Name,
		&i.DiscordUserID,
		&i.CreatedAt,
	)
	return i, err
}
