// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participant_loans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipantLoan = `-- name: CreateParticipantLoan :one
WITH resolved_instance AS (
    SELECT i.id AS instance_internal_id, i.public_id AS instance_id
    FROM instances i
    WHERE i.public_id = $10
), resolved_participant AS (
    SELECT p.id AS participant_internal_id, p.public_id AS participant_id
    FROM participants p
    JOIN resolved_instance ri ON ri.instance_internal_id = p.instance_id
    WHERE p.public_id = $11
), resolved_activity AS (
    SELECT ia.id AS activity_internal_id, ia.public_id AS activity_id
    FROM instance_activities ia
    JOIN resolved_instance ri ON ri.instance_internal_id = ia.instance_id
    WHERE ia.public_id = $12
)
INSERT INTO participant_loans (
    instance_id,
    participant_id,
    activity_id,
    status,
    principal_points,
    interest_points,
    principal_repaid_points,
    interest_repaid_points,
    granted_at,
    due_at,
    settled_at,
    metadata
)
SELECT
    ri.instance_internal_id,
    rp.participant_internal_id,
    ra.activity_internal_id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
FROM resolved_instance ri
CROSS JOIN resolved_participant rp
LEFT JOIN resolved_activity ra ON TRUE
RETURNING
    public_id AS id,
    (SELECT instance_id FROM resolved_instance) AS instance_id,
    (SELECT participant_id FROM resolved_participant) AS participant_id,
    (SELECT activity_id FROM resolved_activity) AS activity_id,
    status,
    principal_points,
    interest_points,
    principal_repaid_points,
    interest_repaid_points,
    granted_at,
    due_at,
    settled_at,
    metadata,
    created_at,
    updated_at
`

type CreateParticipantLoanParams struct {
	Status                string             `json:"status"`
	PrincipalPoints       int32              `json:"principal_points"`
	InterestPoints        int32              `json:"interest_points"`
	PrincipalRepaidPoints int32              `json:"principal_repaid_points"`
	InterestRepaidPoints  int32              `json:"interest_repaid_points"`
	GrantedAt             pgtype.Timestamptz `json:"granted_at"`
	DueAt                 pgtype.Timestamptz `json:"due_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Metadata              []byte             `json:"metadata"`
	InstanceID            pgtype.UUID        `json:"instance_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ActivityID            pgtype.UUID        `json:"activity_id"`
}

type CreateParticipantLoanRow struct {
	ID                    pgtype.UUID        `json:"id"`
	InstanceID            pgtype.UUID        `json:"instance_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ActivityID            pgtype.UUID        `json:"activity_id"`
	Status                string             `json:"status"`
	PrincipalPoints       int32              `json:"principal_points"`
	InterestPoints        int32              `json:"interest_points"`
	PrincipalRepaidPoints int32              `json:"principal_repaid_points"`
	InterestRepaidPoints  int32              `json:"interest_repaid_points"`
	GrantedAt             pgtype.Timestamptz `json:"granted_at"`
	DueAt                 pgtype.Timestamptz `json:"due_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateParticipantLoan(ctx context.Context, arg CreateParticipantLoanParams) (CreateParticipantLoanRow, error) {
	row := q.db.QueryRow(ctx, createParticipantLoan,
		arg.Status,
		arg.PrincipalPoints,
		arg.InterestPoints,
		arg.PrincipalRepaidPoints,
		arg.InterestRepaidPoints,
		arg.GrantedAt,
		arg.DueAt,
		arg.SettledAt,
		arg.Metadata,
		arg.InstanceID,
		arg.ParticipantID,
		arg.ActivityID,
	)
	var i CreateParticipantLoanRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ParticipantID,
		&i.ActivityID,
		&i.Status,
		&i.PrincipalPoints,
		&i.InterestPoints,
		&i.PrincipalRepaidPoints,
		&i.InterestRepaidPoints,
		&i.GrantedAt,
		&i.DueAt,
		&i.SettledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveParticipantLoanByParticipant = `-- name: GetActiveParticipantLoanByParticipant :one
SELECT
    pl.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    ia.public_id AS activity_id,
    pl.status,
    pl.principal_points,
    pl.interest_points,
    pl.principal_repaid_points,
    pl.interest_repaid_points,
    pl.granted_at,
    pl.due_at,
    pl.settled_at,
    pl.metadata,
    pl.created_at,
    pl.updated_at
FROM participant_loans pl
JOIN instances i ON i.id = pl.instance_id
JOIN participants p ON p.id = pl.participant_id
LEFT JOIN instance_activities ia ON ia.id = pl.activity_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND pl.status = 'active'
`

type GetActiveParticipantLoanByParticipantParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
}

type GetActiveParticipantLoanByParticipantRow struct {
	ID                    pgtype.UUID        `json:"id"`
	InstanceID            pgtype.UUID        `json:"instance_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ActivityID            pgtype.UUID        `json:"activity_id"`
	Status                string             `json:"status"`
	PrincipalPoints       int32              `json:"principal_points"`
	InterestPoints        int32              `json:"interest_points"`
	PrincipalRepaidPoints int32              `json:"principal_repaid_points"`
	InterestRepaidPoints  int32              `json:"interest_repaid_points"`
	GrantedAt             pgtype.Timestamptz `json:"granted_at"`
	DueAt                 pgtype.Timestamptz `json:"due_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveParticipantLoanByParticipant(ctx context.Context, arg GetActiveParticipantLoanByParticipantParams) (GetActiveParticipantLoanByParticipantRow, error) {
	row := q.db.QueryRow(ctx, getActiveParticipantLoanByParticipant, arg.InstanceID, arg.ParticipantID)
	var i GetActiveParticipantLoanByParticipantRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ParticipantID,
		&i.ActivityID,
		&i.Status,
		&i.PrincipalPoints,
		&i.InterestPoints,
		&i.PrincipalRepaidPoints,
		&i.InterestRepaidPoints,
		&i.GrantedAt,
		&i.DueAt,
		&i.SettledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveParticipantLoansByInstance = `-- name: ListActiveParticipantLoansByInstance :many
SELECT
    pl.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS participant_id,
    p.name AS participant_name,
    ia.public_id AS activity_id,
    pl.status,
    pl.principal_points,
    pl.interest_points,
    pl.principal_repaid_points,
    pl.interest_repaid_points,
    pl.granted_at,
    pl.due_at,
    pl.settled_at,
    pl.metadata,
    pl.created_at,
    pl.updated_at
FROM participant_loans pl
JOIN instances i ON i.id = pl.instance_id
JOIN participants p ON p.id = pl.participant_id
LEFT JOIN instance_activities ia ON ia.id = pl.activity_id
WHERE i.public_id = $1
  AND pl.status = 'active'
ORDER BY p.name ASC, pl.id ASC
`

type ListActiveParticipantLoansByInstanceRow struct {
	ID                    pgtype.UUID        `json:"id"`
	InstanceID            pgtype.UUID        `json:"instance_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ParticipantName       string             `json:"participant_name"`
	ActivityID            pgtype.UUID        `json:"activity_id"`
	Status                string             `json:"status"`
	PrincipalPoints       int32              `json:"principal_points"`
	InterestPoints        int32              `json:"interest_points"`
	PrincipalRepaidPoints int32              `json:"principal_repaid_points"`
	InterestRepaidPoints  int32              `json:"interest_repaid_points"`
	GrantedAt             pgtype.Timestamptz `json:"granted_at"`
	DueAt                 pgtype.Timestamptz `json:"due_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveParticipantLoansByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListActiveParticipantLoansByInstanceRow, error) {
	rows, err := q.db.Query(ctx, listActiveParticipantLoansByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveParticipantLoansByInstanceRow{}
	for rows.Next() {
		var i ListActiveParticipantLoansByInstanceRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.ActivityID,
			&i.Status,
			&i.PrincipalPoints,
			&i.InterestPoints,
			&i.PrincipalRepaidPoints,
			&i.InterestRepaidPoints,
			&i.GrantedAt,
			&i.DueAt,
			&i.SettledAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParticipantLoan = `-- name: UpdateParticipantLoan :one
UPDATE participant_loans pl
SET status = $1,
    principal_points = $2,
    interest_points = $3,
    principal_repaid_points = $4,
    interest_repaid_points = $5,
    due_at = $6,
    settled_at = $7,
    metadata = $8,
    updated_at = NOW()
WHERE pl.public_id = $9
RETURNING
    pl.public_id AS id,
    (SELECT i.public_id FROM instances i WHERE i.id = pl.instance_id) AS instance_id,
    (SELECT p.public_id FROM participants p WHERE p.id = pl.participant_id) AS participant_id,
    (SELECT ia.public_id FROM instance_activities ia WHERE ia.id = pl.activity_id) AS activity_id,
    pl.status,
    pl.principal_points,
    pl.interest_points,
    pl.principal_repaid_points,
    pl.interest_repaid_points,
    pl.granted_at,
    pl.due_at,
    pl.settled_at,
    pl.metadata,
    pl.created_at,
    pl.updated_at
`

type UpdateParticipantLoanParams struct {
	Status                string             `json:"status"`
	PrincipalPoints       int32              `json:"principal_points"`
	InterestPoints        int32              `json:"interest_points"`
	PrincipalRepaidPoints int32              `json:"principal_repaid_points"`
	InterestRepaidPoints  int32              `json:"interest_repaid_points"`
	DueAt                 pgtype.Timestamptz `json:"due_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Metadata              []byte             `json:"metadata"`
	ID                    pgtype.UUID        `json:"id"`
}

type UpdateParticipantLoanRow struct {
	ID                    pgtype.UUID        `json:"id"`
	InstanceID            pgtype.UUID        `json:"instance_id"`
	ParticipantID         pgtype.UUID        `json:"participant_id"`
	ActivityID            pgtype.UUID        `json:"activity_id"`
	Status                string             `json:"status"`
	PrincipalPoints       int32              `json:"principal_points"`
	InterestPoints        int32              `json:"interest_points"`
	PrincipalRepaidPoints int32              `json:"principal_repaid_points"`
	InterestRepaidPoints  int32              `json:"interest_repaid_points"`
	GrantedAt             pgtype.Timestamptz `json:"granted_at"`
	DueAt                 pgtype.Timestamptz `json:"due_at"`
	SettledAt             pgtype.Timestamptz `json:"settled_at"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateParticipantLoan(ctx context.Context, arg UpdateParticipantLoanParams) (UpdateParticipantLoanRow, error) {
	row := q.db.QueryRow(ctx, updateParticipantLoan,
		arg.Status,
		arg.PrincipalPoints,
		arg.InterestPoints,
		arg.PrincipalRepaidPoints,
		arg.InterestRepaidPoints,
		arg.DueAt,
		arg.SettledAt,
		arg.Metadata,
		arg.ID,
	)
	var i UpdateParticipantLoanRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ParticipantID,
		&i.ActivityID,
		&i.Status,
		&i.PrincipalPoints,
		&i.InterestPoints,
		&i.PrincipalRepaidPoints,
		&i.InterestRepaidPoints,
		&i.GrantedAt,
		&i.DueAt,
		&i.SettledAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
