// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pony_ownerships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParticipantPonyOwnership = `-- name: CreateParticipantPonyOwnership :one
WITH resolved_instance AS (
    SELECT i.id AS instance_internal_id, i.public_id AS instance_id
    FROM instances i
    WHERE i.public_id = $5
), resolved_owner AS (
    SELECT p.id AS owner_internal_id, p.public_id AS owner_participant_id
    FROM participants p
    JOIN resolved_instance ri ON ri.instance_internal_id = p.instance_id
    WHERE p.public_id = $6
), resolved_contestant AS (
    SELECT c.id AS contestant_internal_id, c.public_id AS contestant_id
    FROM contestants c
    JOIN instance_contestants ic ON ic.contestant_id = c.id
    JOIN resolved_instance ri ON ri.instance_internal_id = ic.instance_id
    WHERE c.public_id = $7
), resolved_occurrence AS (
    SELECT ao.id AS occurrence_internal_id, ao.public_id AS source_activity_occurrence_id
    FROM activity_occurrences ao
    JOIN instance_activities ia ON ia.id = ao.activity_id
    JOIN resolved_instance ri ON ri.instance_internal_id = ia.instance_id
    WHERE ao.public_id = $8
)
INSERT INTO participant_pony_ownerships (
    instance_id,
    owner_participant_id,
    contestant_id,
    source_activity_occurrence_id,
    acquired_at,
    released_at,
    status,
    metadata
)
SELECT
    ri.instance_internal_id,
    ro.owner_internal_id,
    rc.contestant_internal_id,
    rao.occurrence_internal_id,
    $1,
    $2,
    $3,
    $4
FROM resolved_instance ri
CROSS JOIN resolved_owner ro
CROSS JOIN resolved_contestant rc
LEFT JOIN resolved_occurrence rao ON TRUE
RETURNING
    public_id AS id,
    (SELECT instance_id FROM resolved_instance) AS instance_id,
    (SELECT owner_participant_id FROM resolved_owner) AS owner_participant_id,
    (SELECT contestant_id FROM resolved_contestant) AS contestant_id,
    (SELECT source_activity_occurrence_id FROM resolved_occurrence) AS source_activity_occurrence_id,
    acquired_at,
    released_at,
    status,
    metadata,
    created_at,
    updated_at
`

type CreateParticipantPonyOwnershipParams struct {
	AcquiredAt                 pgtype.Timestamptz `json:"acquired_at"`
	ReleasedAt                 pgtype.Timestamptz `json:"released_at"`
	Status                     string             `json:"status"`
	Metadata                   []byte             `json:"metadata"`
	InstanceID                 pgtype.UUID        `json:"instance_id"`
	OwnerParticipantID         pgtype.UUID        `json:"owner_participant_id"`
	ContestantID               pgtype.UUID        `json:"contestant_id"`
	SourceActivityOccurrenceID pgtype.UUID        `json:"source_activity_occurrence_id"`
}

type CreateParticipantPonyOwnershipRow struct {
	ID                         pgtype.UUID        `json:"id"`
	InstanceID                 pgtype.UUID        `json:"instance_id"`
	OwnerParticipantID         pgtype.UUID        `json:"owner_participant_id"`
	ContestantID               pgtype.UUID        `json:"contestant_id"`
	SourceActivityOccurrenceID pgtype.UUID        `json:"source_activity_occurrence_id"`
	AcquiredAt                 pgtype.Timestamptz `json:"acquired_at"`
	ReleasedAt                 pgtype.Timestamptz `json:"released_at"`
	Status                     string             `json:"status"`
	Metadata                   []byte             `json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateParticipantPonyOwnership(ctx context.Context, arg CreateParticipantPonyOwnershipParams) (CreateParticipantPonyOwnershipRow, error) {
	row := q.db.QueryRow(ctx, createParticipantPonyOwnership,
		arg.AcquiredAt,
		arg.ReleasedAt,
		arg.Status,
		arg.Metadata,
		arg.InstanceID,
		arg.OwnerParticipantID,
		arg.ContestantID,
		arg.SourceActivityOccurrenceID,
	)
	var i CreateParticipantPonyOwnershipRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.OwnerParticipantID,
		&i.ContestantID,
		&i.SourceActivityOccurrenceID,
		&i.AcquiredAt,
		&i.ReleasedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveParticipantPonyOwnershipsByContestantAt = `-- name: ListActiveParticipantPonyOwnershipsByContestantAt :many
SELECT
    ppo.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS owner_participant_id,
    p.name AS owner_participant_name,
    c.public_id AS contestant_id,
    c.name AS contestant_name,
    ao.public_id AS source_activity_occurrence_id,
    ppo.acquired_at,
    ppo.released_at,
    ppo.status,
    ppo.metadata,
    ppo.created_at,
    ppo.updated_at
FROM participant_pony_ownerships ppo
JOIN instances i ON i.id = ppo.instance_id
JOIN participants p ON p.id = ppo.owner_participant_id
JOIN contestants c ON c.id = ppo.contestant_id
LEFT JOIN activity_occurrences ao ON ao.id = ppo.source_activity_occurrence_id
WHERE i.public_id = $1
  AND c.public_id = $2
  AND ppo.status = 'active'
  AND ppo.acquired_at <= $3
  AND (ppo.released_at IS NULL OR ppo.released_at > $3)
ORDER BY p.name ASC, ppo.id ASC
`

type ListActiveParticipantPonyOwnershipsByContestantAtParams struct {
	InstanceID   pgtype.UUID        `json:"instance_id"`
	ContestantID pgtype.UUID        `json:"contestant_id"`
	At           pgtype.Timestamptz `json:"at"`
}

type ListActiveParticipantPonyOwnershipsByContestantAtRow struct {
	ID                         pgtype.UUID        `json:"id"`
	InstanceID                 pgtype.UUID        `json:"instance_id"`
	OwnerParticipantID         pgtype.UUID        `json:"owner_participant_id"`
	OwnerParticipantName       string             `json:"owner_participant_name"`
	ContestantID               pgtype.UUID        `json:"contestant_id"`
	ContestantName             string             `json:"contestant_name"`
	SourceActivityOccurrenceID pgtype.UUID        `json:"source_activity_occurrence_id"`
	AcquiredAt                 pgtype.Timestamptz `json:"acquired_at"`
	ReleasedAt                 pgtype.Timestamptz `json:"released_at"`
	Status                     string             `json:"status"`
	Metadata                   []byte             `json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveParticipantPonyOwnershipsByContestantAt(ctx context.Context, arg ListActiveParticipantPonyOwnershipsByContestantAtParams) ([]ListActiveParticipantPonyOwnershipsByContestantAtRow, error) {
	rows, err := q.db.Query(ctx, listActiveParticipantPonyOwnershipsByContestantAt, arg.InstanceID, arg.ContestantID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveParticipantPonyOwnershipsByContestantAtRow{}
	for rows.Next() {
		var i ListActiveParticipantPonyOwnershipsByContestantAtRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.OwnerParticipantID,
			&i.OwnerParticipantName,
			&i.ContestantID,
			&i.ContestantName,
			&i.SourceActivityOccurrenceID,
			&i.AcquiredAt,
			&i.ReleasedAt,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveParticipantPonyOwnershipsByOwnerAt = `-- name: ListActiveParticipantPonyOwnershipsByOwnerAt :many
SELECT
    ppo.public_id AS id,
    i.public_id AS instance_id,
    p.public_id AS owner_participant_id,
    p.name AS owner_participant_name,
    c.public_id AS contestant_id,
    c.name AS contestant_name,
    ao.public_id AS source_activity_occurrence_id,
    ppo.acquired_at,
    ppo.released_at,
    ppo.status,
    ppo.metadata,
    ppo.created_at,
    ppo.updated_at
FROM participant_pony_ownerships ppo
JOIN instances i ON i.id = ppo.instance_id
JOIN participants p ON p.id = ppo.owner_participant_id
JOIN contestants c ON c.id = ppo.contestant_id
LEFT JOIN activity_occurrences ao ON ao.id = ppo.source_activity_occurrence_id
WHERE i.public_id = $1
  AND p.public_id = $2
  AND ppo.status = 'active'
  AND ppo.acquired_at <= $3
  AND (ppo.released_at IS NULL OR ppo.released_at > $3)
ORDER BY c.name ASC, ppo.id ASC
`

type ListActiveParticipantPonyOwnershipsByOwnerAtParams struct {
	InstanceID         pgtype.UUID        `json:"instance_id"`
	OwnerParticipantID pgtype.UUID        `json:"owner_participant_id"`
	At                 pgtype.Timestamptz `json:"at"`
}

type ListActiveParticipantPonyOwnershipsByOwnerAtRow struct {
	ID                         pgtype.UUID        `json:"id"`
	InstanceID                 pgtype.UUID        `json:"instance_id"`
	OwnerParticipantID         pgtype.UUID        `json:"owner_participant_id"`
	OwnerParticipantName       string             `json:"owner_participant_name"`
	ContestantID               pgtype.UUID        `json:"contestant_id"`
	ContestantName             string             `json:"contestant_name"`
	SourceActivityOccurrenceID pgtype.UUID        `json:"source_activity_occurrence_id"`
	AcquiredAt                 pgtype.Timestamptz `json:"acquired_at"`
	ReleasedAt                 pgtype.Timestamptz `json:"released_at"`
	Status                     string             `json:"status"`
	Metadata                   []byte             `json:"metadata"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveParticipantPonyOwnershipsByOwnerAt(ctx context.Context, arg ListActiveParticipantPonyOwnershipsByOwnerAtParams) ([]ListActiveParticipantPonyOwnershipsByOwnerAtRow, error) {
	rows, err := q.db.Query(ctx, listActiveParticipantPonyOwnershipsByOwnerAt, arg.InstanceID, arg.OwnerParticipantID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveParticipantPonyOwnershipsByOwnerAtRow{}
	for rows.Next() {
		var i ListActiveParticipantPonyOwnershipsByOwnerAtRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.OwnerParticipantID,
			&i.OwnerParticipantName,
			&i.ContestantID,
			&i.ContestantName,
			&i.SourceActivityOccurrenceID,
			&i.AcquiredAt,
			&i.ReleasedAt,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
