// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progression.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProgressionCommand = `-- name: CreateProgressionCommand :one
INSERT INTO instance_progression_commands (
    instance_id,
    command_key,
    operation,
    actor_discord_user_id,
    effective_at,
    payload_hash,
    payload,
    response
)
SELECT
    i.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM instances i
WHERE i.public_id = $8
RETURNING id, command_key, operation, actor_discord_user_id, effective_at, payload_hash, payload, response, created_at
`

type CreateProgressionCommandParams struct {
	CommandKey         string             `json:"command_key"`
	Operation          string             `json:"operation"`
	ActorDiscordUserID string             `json:"actor_discord_user_id"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	PayloadHash        string             `json:"payload_hash"`
	Payload            []byte             `json:"payload"`
	Response           []byte             `json:"response"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
}

type CreateProgressionCommandRow struct {
	ID                 int64              `json:"id"`
	CommandKey         string             `json:"command_key"`
	Operation          string             `json:"operation"`
	ActorDiscordUserID string             `json:"actor_discord_user_id"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	PayloadHash        string             `json:"payload_hash"`
	Payload            []byte             `json:"payload"`
	Response           []byte             `json:"response"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProgressionCommand(ctx context.Context, arg CreateProgressionCommandParams) (CreateProgressionCommandRow, error) {
	row := q.db.QueryRow(ctx, createProgressionCommand,
		arg.CommandKey,
		arg.Operation,
		arg.ActorDiscordUserID,
		arg.EffectiveAt,
		arg.PayloadHash,
		arg.Payload,
		arg.Response,
		arg.InstanceID,
	)
	var i CreateProgressionCommandRow
	err := row.Scan(
		&i.ID,
		&i.CommandKey,
		&i.Operation,
		&i.ActorDiscordUserID,
		&i.EffectiveAt,
		&i.PayloadHash,
		&i.Payload,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getInstanceDraftProgress = `-- name: GetInstanceDraftProgress :one
SELECT
    i.public_id AS instance_id,
    idp.status,
    idp.opened_at,
    idp.closed_at,
    idp.updated_at
FROM instance_draft_progress idp
JOIN instances i ON i.id = idp.instance_id
WHERE i.public_id = $1
`

type GetInstanceDraftProgressRow struct {
	InstanceID pgtype.UUID        `json:"instance_id"`
	Status     string             `json:"status"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetInstanceDraftProgress(ctx context.Context, instanceID pgtype.UUID) (GetInstanceDraftProgressRow, error) {
	row := q.db.QueryRow(ctx, getInstanceDraftProgress, instanceID)
	var i GetInstanceDraftProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceEpisodeProgress = `-- name: GetInstanceEpisodeProgress :one
SELECT
    i.public_id AS instance_id,
    iep.episode_number,
    iep.status,
    iep.started_at,
    iep.completed_at,
    iep.scored_at,
    iep.updated_at
FROM instance_episode_progress iep
JOIN instances i ON i.id = iep.instance_id
WHERE i.public_id = $1
  AND iep.episode_number = $2
`

type GetInstanceEpisodeProgressParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	EpisodeNumber int32       `json:"episode_number"`
}

type GetInstanceEpisodeProgressRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ScoredAt      pgtype.Timestamptz `json:"scored_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetInstanceEpisodeProgress(ctx context.Context, arg GetInstanceEpisodeProgressParams) (GetInstanceEpisodeProgressRow, error) {
	row := q.db.QueryRow(ctx, getInstanceEpisodeProgress, arg.InstanceID, arg.EpisodeNumber)
	var i GetInstanceEpisodeProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ScoredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstanceProgressionMode = `-- name: GetInstanceProgressionMode :one
SELECT progression_mode
FROM instances
WHERE public_id = $1
`

func (q *Queries) GetInstanceProgressionMode(ctx context.Context, instanceID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getInstanceProgressionMode, instanceID)
	var progression_mode string
	err := row.Scan(&progression_mode)
	return progression_mode, err
}

const getLatestManagedEpisodeBrief = `-- name: GetLatestManagedEpisodeBrief :one
SELECT
    ie.public_id AS id,
    i.public_id AS instance_id,
    ie.episode_number,
    ie.label,
    ie.airs_at,
    ie.metadata,
    ie.created_at,
    ie.updated_at
FROM instance_episode_progress iep
JOIN instance_episodes ie
  ON ie.instance_id = iep.instance_id
 AND ie.episode_number = iep.episode_number
JOIN instances i ON i.id = ie.instance_id
WHERE i.public_id = $1
  AND iep.status IN ('started', 'completed', 'scored')
ORDER BY iep.episode_number DESC
LIMIT 1
`

type GetLatestManagedEpisodeBriefRow struct {
	ID            pgtype.UUID        `json:"id"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Label         string             `json:"label"`
	AirsAt        pgtype.Timestamptz `json:"airs_at"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLatestManagedEpisodeBrief(ctx context.Context, instanceID pgtype.UUID) (GetLatestManagedEpisodeBriefRow, error) {
	row := q.db.QueryRow(ctx, getLatestManagedEpisodeBrief, instanceID)
	var i GetLatestManagedEpisodeBriefRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Label,
		&i.AirsAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestManagedEpisodeProgress = `-- name: GetLatestManagedEpisodeProgress :one
SELECT
    i.public_id AS instance_id,
    iep.episode_number,
    iep.status,
    iep.started_at,
    iep.completed_at,
    iep.scored_at,
    iep.updated_at
FROM instance_episode_progress iep
JOIN instances i ON i.id = iep.instance_id
WHERE i.public_id = $1
  AND iep.status IN ('started', 'completed', 'scored')
ORDER BY iep.episode_number DESC
LIMIT 1
`

type GetLatestManagedEpisodeProgressRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ScoredAt      pgtype.Timestamptz `json:"scored_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetLatestManagedEpisodeProgress(ctx context.Context, instanceID pgtype.UUID) (GetLatestManagedEpisodeProgressRow, error) {
	row := q.db.QueryRow(ctx, getLatestManagedEpisodeProgress, instanceID)
	var i GetLatestManagedEpisodeProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ScoredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreviousInstanceEpisodeProgress = `-- name: GetPreviousInstanceEpisodeProgress :one
SELECT
    i.public_id AS instance_id,
    iep.episode_number,
    iep.status,
    iep.started_at,
    iep.completed_at,
    iep.scored_at,
    iep.updated_at
FROM instance_episode_progress iep
JOIN instances i ON i.id = iep.instance_id
WHERE i.public_id = $1
  AND iep.episode_number > 0
  AND iep.episode_number < $2
ORDER BY iep.episode_number DESC
LIMIT 1
`

type GetPreviousInstanceEpisodeProgressParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	EpisodeNumber int32       `json:"episode_number"`
}

type GetPreviousInstanceEpisodeProgressRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ScoredAt      pgtype.Timestamptz `json:"scored_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPreviousInstanceEpisodeProgress(ctx context.Context, arg GetPreviousInstanceEpisodeProgressParams) (GetPreviousInstanceEpisodeProgressRow, error) {
	row := q.db.QueryRow(ctx, getPreviousInstanceEpisodeProgress, arg.InstanceID, arg.EpisodeNumber)
	var i GetPreviousInstanceEpisodeProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ScoredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgressionCommand = `-- name: GetProgressionCommand :one
SELECT
    ipc.id,
    i.public_id AS instance_id,
    ipc.command_key,
    ipc.operation,
    ipc.actor_discord_user_id,
    ipc.effective_at,
    ipc.payload_hash,
    ipc.payload,
    ipc.response,
    ipc.created_at
FROM instance_progression_commands ipc
JOIN instances i ON i.id = ipc.instance_id
WHERE i.public_id = $1
  AND ipc.command_key = $2
`

type GetProgressionCommandParams struct {
	InstanceID pgtype.UUID `json:"instance_id"`
	CommandKey string      `json:"command_key"`
}

type GetProgressionCommandRow struct {
	ID                 int64              `json:"id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	CommandKey         string             `json:"command_key"`
	Operation          string             `json:"operation"`
	ActorDiscordUserID string             `json:"actor_discord_user_id"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	PayloadHash        string             `json:"payload_hash"`
	Payload            []byte             `json:"payload"`
	Response           []byte             `json:"response"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetProgressionCommand(ctx context.Context, arg GetProgressionCommandParams) (GetProgressionCommandRow, error) {
	row := q.db.QueryRow(ctx, getProgressionCommand, arg.InstanceID, arg.CommandKey)
	var i GetProgressionCommandRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.CommandKey,
		&i.Operation,
		&i.ActorDiscordUserID,
		&i.EffectiveAt,
		&i.PayloadHash,
		&i.Payload,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const initializeInstanceDraftProgress = `-- name: InitializeInstanceDraftProgress :exec
INSERT INTO instance_draft_progress (instance_id)
SELECT id
FROM instances
WHERE public_id = $1
ON CONFLICT (instance_id) DO NOTHING
`

func (q *Queries) InitializeInstanceDraftProgress(ctx context.Context, instanceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, initializeInstanceDraftProgress, instanceID)
	return err
}

const initializeInstanceEpisodeProgress = `-- name: InitializeInstanceEpisodeProgress :exec
INSERT INTO instance_episode_progress (instance_id, episode_number)
SELECT ie.instance_id, ie.episode_number
FROM instance_episodes ie
JOIN instances i ON i.id = ie.instance_id
WHERE i.public_id = $1
ON CONFLICT (instance_id, episode_number) DO NOTHING
`

func (q *Queries) InitializeInstanceEpisodeProgress(ctx context.Context, instanceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, initializeInstanceEpisodeProgress, instanceID)
	return err
}

const lockInstanceDraftProgress = `-- name: LockInstanceDraftProgress :one
SELECT
    i.public_id AS instance_id,
    idp.status,
    idp.opened_at,
    idp.closed_at,
    idp.updated_at
FROM instance_draft_progress idp
JOIN instances i ON i.id = idp.instance_id
WHERE i.public_id = $1
FOR UPDATE
`

type LockInstanceDraftProgressRow struct {
	InstanceID pgtype.UUID        `json:"instance_id"`
	Status     string             `json:"status"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockInstanceDraftProgress(ctx context.Context, instanceID pgtype.UUID) (LockInstanceDraftProgressRow, error) {
	row := q.db.QueryRow(ctx, lockInstanceDraftProgress, instanceID)
	var i LockInstanceDraftProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockInstanceEpisodeProgress = `-- name: LockInstanceEpisodeProgress :one
SELECT
    i.public_id AS instance_id,
    iep.episode_number,
    iep.status,
    iep.started_at,
    iep.completed_at,
    iep.scored_at,
    iep.updated_at
FROM instance_episode_progress iep
JOIN instances i ON i.id = iep.instance_id
WHERE i.public_id = $1
  AND iep.episode_number = $2
FOR UPDATE
`

type LockInstanceEpisodeProgressParams struct {
	InstanceID    pgtype.UUID `json:"instance_id"`
	EpisodeNumber int32       `json:"episode_number"`
}

type LockInstanceEpisodeProgressRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ScoredAt      pgtype.Timestamptz `json:"scored_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockInstanceEpisodeProgress(ctx context.Context, arg LockInstanceEpisodeProgressParams) (LockInstanceEpisodeProgressRow, error) {
	row := q.db.QueryRow(ctx, lockInstanceEpisodeProgress, arg.InstanceID, arg.EpisodeNumber)
	var i LockInstanceEpisodeProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ScoredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockInstanceForProgression = `-- name: LockInstanceForProgression :one
SELECT public_id AS id, progression_mode
FROM instances
WHERE public_id = $1
FOR UPDATE
`

type LockInstanceForProgressionRow struct {
	ID              pgtype.UUID `json:"id"`
	ProgressionMode string      `json:"progression_mode"`
}

func (q *Queries) LockInstanceForProgression(ctx context.Context, instanceID pgtype.UUID) (LockInstanceForProgressionRow, error) {
	row := q.db.QueryRow(ctx, lockInstanceForProgression, instanceID)
	var i LockInstanceForProgressionRow
	err := row.Scan(&i.ID, &i.ProgressionMode)
	return i, err
}

const setInstanceProgressionMode = `-- name: SetInstanceProgressionMode :exec
UPDATE instances
SET progression_mode = $1
WHERE public_id = $2
`

type SetInstanceProgressionModeParams struct {
	ProgressionMode string      `json:"progression_mode"`
	InstanceID      pgtype.UUID `json:"instance_id"`
}

func (q *Queries) SetInstanceProgressionMode(ctx context.Context, arg SetInstanceProgressionModeParams) error {
	_, err := q.db.Exec(ctx, setInstanceProgressionMode, arg.ProgressionMode, arg.InstanceID)
	return err
}

const updateInstanceDraftProgress = `-- name: UpdateInstanceDraftProgress :one
UPDATE instance_draft_progress idp
SET status = $1,
    opened_at = $2,
    closed_at = $3,
    updated_at = NOW()
FROM instances i
WHERE idp.instance_id = i.id
  AND i.public_id = $4
RETURNING
    i.public_id AS instance_id,
    idp.status,
    idp.opened_at,
    idp.closed_at,
    idp.updated_at
`

type UpdateInstanceDraftProgressParams struct {
	Status     string             `json:"status"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	InstanceID pgtype.UUID        `json:"instance_id"`
}

type UpdateInstanceDraftProgressRow struct {
	InstanceID pgtype.UUID        `json:"instance_id"`
	Status     string             `json:"status"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateInstanceDraftProgress(ctx context.Context, arg UpdateInstanceDraftProgressParams) (UpdateInstanceDraftProgressRow, error) {
	row := q.db.QueryRow(ctx, updateInstanceDraftProgress,
		arg.Status,
		arg.OpenedAt,
		arg.ClosedAt,
		arg.InstanceID,
	)
	var i UpdateInstanceDraftProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInstanceEpisodeProgress = `-- name: UpdateInstanceEpisodeProgress :one
UPDATE instance_episode_progress iep
SET status = $1,
    started_at = $2,
    completed_at = $3,
    scored_at = $4,
    updated_at = NOW()
FROM instances i
WHERE iep.instance_id = i.id
  AND i.public_id = $5
  AND iep.episode_number = $6
RETURNING
    i.public_id AS instance_id,
    iep.episode_number,
    iep.status,
    iep.started_at,
    iep.completed_at,
    iep.scored_at,
    iep.updated_at
`

type UpdateInstanceEpisodeProgressParams struct {
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ScoredAt      pgtype.Timestamptz `json:"scored_at"`
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
}

type UpdateInstanceEpisodeProgressRow struct {
	InstanceID    pgtype.UUID        `json:"instance_id"`
	EpisodeNumber int32              `json:"episode_number"`
	Status        string             `json:"status"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ScoredAt      pgtype.Timestamptz `json:"scored_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateInstanceEpisodeProgress(ctx context.Context, arg UpdateInstanceEpisodeProgressParams) (UpdateInstanceEpisodeProgressRow, error) {
	row := q.db.QueryRow(ctx, updateInstanceEpisodeProgress,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ScoredAt,
		arg.InstanceID,
		arg.EpisodeNumber,
	)
	var i UpdateInstanceEpisodeProgressRow
	err := row.Scan(
		&i.InstanceID,
		&i.EpisodeNumber,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ScoredAt,
		&i.UpdatedAt,
	)
	return i, err
}
