// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateContestant(ctx context.Context, arg CreateContestantParams) (CreateContestantRow, error)
	CreateDraftPick(ctx context.Context, arg CreateDraftPickParams) (CreateDraftPickRow, error)
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (CreateInstanceRow, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (CreateParticipantRow, error)
	DeleteDraftPicksForParticipant(ctx context.Context, participantID pgtype.UUID) error
	DeleteInstanceByNameSeason(ctx context.Context, arg DeleteInstanceByNameSeasonParams) error
	GetContestant(ctx context.Context, id pgtype.UUID) (GetContestantRow, error)
	GetInstance(ctx context.Context, id pgtype.UUID) (GetInstanceRow, error)
	GetParticipant(ctx context.Context, id pgtype.UUID) (GetParticipantRow, error)
	InstanceHasContestant(ctx context.Context, arg InstanceHasContestantParams) (bool, error)
	ListContestantsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListContestantsByInstanceRow, error)
	ListContestantsGlobal(ctx context.Context) ([]ListContestantsGlobalRow, error)
	ListDraftPicksForInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListDraftPicksForInstanceRow, error)
	ListDraftPicksForParticipant(ctx context.Context, participantID pgtype.UUID) ([]ListDraftPicksForParticipantRow, error)
	ListInstances(ctx context.Context) ([]ListInstancesRow, error)
	ListOutcomePositionsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListOutcomePositionsByInstanceRow, error)
	ListParticipantsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListParticipantsByInstanceRow, error)
	UpsertOutcomePosition(ctx context.Context, arg UpsertOutcomePositionParams) (UpsertOutcomePositionRow, error)
}

var _ Querier = (*Queries)(nil)
