// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateActivityGroupAssignment(ctx context.Context, arg CreateActivityGroupAssignmentParams) (CreateActivityGroupAssignmentRow, error)
	CreateActivityOccurrence(ctx context.Context, arg CreateActivityOccurrenceParams) (CreateActivityOccurrenceRow, error)
	CreateActivityOccurrenceGroup(ctx context.Context, arg CreateActivityOccurrenceGroupParams) (CreateActivityOccurrenceGroupRow, error)
	CreateActivityOccurrenceParticipant(ctx context.Context, arg CreateActivityOccurrenceParticipantParams) (CreateActivityOccurrenceParticipantRow, error)
	CreateActivityParticipantAssignment(ctx context.Context, arg CreateActivityParticipantAssignmentParams) (CreateActivityParticipantAssignmentRow, error)
	CreateBonusPointLedgerEntry(ctx context.Context, arg CreateBonusPointLedgerEntryParams) (CreateBonusPointLedgerEntryRow, error)
	CreateContestant(ctx context.Context, arg CreateContestantParams) (CreateContestantRow, error)
	CreateDraftPick(ctx context.Context, arg CreateDraftPickParams) (CreateDraftPickRow, error)
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (CreateInstanceRow, error)
	CreateInstanceActivity(ctx context.Context, arg CreateInstanceActivityParams) (CreateInstanceActivityRow, error)
	CreateInstanceEpisode(ctx context.Context, arg CreateInstanceEpisodeParams) (CreateInstanceEpisodeRow, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (CreateParticipantRow, error)
	CreateParticipantAdvantage(ctx context.Context, arg CreateParticipantAdvantageParams) (CreateParticipantAdvantageRow, error)
	CreateParticipantGroup(ctx context.Context, arg CreateParticipantGroupParams) (CreateParticipantGroupRow, error)
	CreateParticipantGroupMembershipPeriod(ctx context.Context, arg CreateParticipantGroupMembershipPeriodParams) (CreateParticipantGroupMembershipPeriodRow, error)
	DeleteDraftPicksForParticipant(ctx context.Context, participantID pgtype.UUID) error
	DeleteInstanceByNameSeason(ctx context.Context, arg DeleteInstanceByNameSeasonParams) error
	GetActivityOccurrence(ctx context.Context, id pgtype.UUID) (GetActivityOccurrenceRow, error)
	GetAvailableSecretBalanceByParticipant(ctx context.Context, arg GetAvailableSecretBalanceByParticipantParams) (int32, error)
	GetContestant(ctx context.Context, id pgtype.UUID) (GetContestantRow, error)
	GetCurrentEpisodeAt(ctx context.Context, arg GetCurrentEpisodeAtParams) (GetCurrentEpisodeAtRow, error)
	GetInstance(ctx context.Context, id pgtype.UUID) (GetInstanceRow, error)
	GetInstanceActivity(ctx context.Context, id pgtype.UUID) (GetInstanceActivityRow, error)
	GetParticipant(ctx context.Context, id pgtype.UUID) (GetParticipantRow, error)
	GetParticipantGroup(ctx context.Context, id pgtype.UUID) (GetParticipantGroupRow, error)
	GetSecretBonusTotalByParticipant(ctx context.Context, arg GetSecretBonusTotalByParticipantParams) (int32, error)
	GetVisibleBonusTotalByParticipant(ctx context.Context, arg GetVisibleBonusTotalByParticipantParams) (int32, error)
	GetVisibleBonusTotalByParticipantAsOf(ctx context.Context, arg GetVisibleBonusTotalByParticipantAsOfParams) (int32, error)
	InstanceHasContestant(ctx context.Context, arg InstanceHasContestantParams) (bool, error)
	ListActiveActivityGroupAssignmentsAt(ctx context.Context, arg ListActiveActivityGroupAssignmentsAtParams) ([]ListActiveActivityGroupAssignmentsAtRow, error)
	ListActiveActivityParticipantAssignmentsAt(ctx context.Context, arg ListActiveActivityParticipantAssignmentsAtParams) ([]ListActiveActivityParticipantAssignmentsAtRow, error)
	ListActiveAdvantagesByTypeForGroup(ctx context.Context, arg ListActiveAdvantagesByTypeForGroupParams) ([]ListActiveAdvantagesByTypeForGroupRow, error)
	ListActiveAdvantagesByTypeForParticipant(ctx context.Context, arg ListActiveAdvantagesByTypeForParticipantParams) ([]ListActiveAdvantagesByTypeForParticipantRow, error)
	ListActiveParticipantGroupMembershipsAt(ctx context.Context, arg ListActiveParticipantGroupMembershipsAtParams) ([]ListActiveParticipantGroupMembershipsAtRow, error)
	ListActivityGroupAssignments(ctx context.Context, activityID pgtype.UUID) ([]ListActivityGroupAssignmentsRow, error)
	ListActivityOccurrenceGroups(ctx context.Context, activityOccurrenceID pgtype.UUID) ([]ListActivityOccurrenceGroupsRow, error)
	ListActivityOccurrenceParticipants(ctx context.Context, activityOccurrenceID pgtype.UUID) ([]ListActivityOccurrenceParticipantsRow, error)
	ListActivityOccurrencesByActivity(ctx context.Context, activityID pgtype.UUID) ([]ListActivityOccurrencesByActivityRow, error)
	ListActivityParticipantAssignments(ctx context.Context, activityID pgtype.UUID) ([]ListActivityParticipantAssignmentsRow, error)
	ListAllBonusPointLedgerEntriesForParticipant(ctx context.Context, arg ListAllBonusPointLedgerEntriesForParticipantParams) ([]ListAllBonusPointLedgerEntriesForParticipantRow, error)
	ListContestantsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListContestantsByInstanceRow, error)
	ListContestantsGlobal(ctx context.Context) ([]ListContestantsGlobalRow, error)
	ListDraftPicksForInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListDraftPicksForInstanceRow, error)
	ListDraftPicksForParticipant(ctx context.Context, participantID pgtype.UUID) ([]ListDraftPicksForParticipantRow, error)
	ListEpisodeBoundaryWindows(ctx context.Context, instanceID pgtype.UUID) ([]ListEpisodeBoundaryWindowsRow, error)
	ListInstanceActivitiesByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListInstanceActivitiesByInstanceRow, error)
	ListInstanceEpisodes(ctx context.Context, instanceID pgtype.UUID) ([]ListInstanceEpisodesRow, error)
	ListInstances(ctx context.Context) ([]ListInstancesRow, error)
	ListOutcomePositionsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListOutcomePositionsByInstanceRow, error)
	ListParticipantGroupMembershipPeriods(ctx context.Context, participantGroupID pgtype.UUID) ([]ListParticipantGroupMembershipPeriodsRow, error)
	ListParticipantGroupsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListParticipantGroupsByInstanceRow, error)
	ListParticipantsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]ListParticipantsByInstanceRow, error)
	ListVisibleBonusPointLedgerEntriesForParticipant(ctx context.Context, arg ListVisibleBonusPointLedgerEntriesForParticipantParams) ([]ListVisibleBonusPointLedgerEntriesForParticipantRow, error)
	MarkAdvantageUsed(ctx context.Context, id pgtype.UUID) error
	UpdateInstanceName(ctx context.Context, arg UpdateInstanceNameParams) (UpdateInstanceNameRow, error)
	UpsertOutcomePosition(ctx context.Context, arg UpsertOutcomePositionParams) (UpsertOutcomePositionRow, error)
}

var _ Querier = (*Queries)(nil)
