// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstanceScoreRevision = `-- name: CreateInstanceScoreRevision :one
INSERT INTO instance_score_revisions (
    instance_id,
    revision_number,
    episode_number,
    reason,
    effective_at,
    input_snapshot
)
SELECT
    i.id,
    $1,
    $2,
    $3,
    $4,
    $5
FROM instances i
WHERE i.public_id = $6
RETURNING id, public_id, revision_number, episode_number, reason, effective_at, input_snapshot, created_at
`

type CreateInstanceScoreRevisionParams struct {
	RevisionNumber int32              `json:"revision_number"`
	EpisodeNumber  int32              `json:"episode_number"`
	Reason         string             `json:"reason"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	InputSnapshot  []byte             `json:"input_snapshot"`
	InstanceID     pgtype.UUID        `json:"instance_id"`
}

type CreateInstanceScoreRevisionRow struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	RevisionNumber int32              `json:"revision_number"`
	EpisodeNumber  int32              `json:"episode_number"`
	Reason         string             `json:"reason"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	InputSnapshot  []byte             `json:"input_snapshot"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInstanceScoreRevision(ctx context.Context, arg CreateInstanceScoreRevisionParams) (CreateInstanceScoreRevisionRow, error) {
	row := q.db.QueryRow(ctx, createInstanceScoreRevision,
		arg.RevisionNumber,
		arg.EpisodeNumber,
		arg.Reason,
		arg.EffectiveAt,
		arg.InputSnapshot,
		arg.InstanceID,
	)
	var i CreateInstanceScoreRevisionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RevisionNumber,
		&i.EpisodeNumber,
		&i.Reason,
		&i.EffectiveAt,
		&i.InputSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const createInstanceScoreRevisionRow = `-- name: CreateInstanceScoreRevisionRow :exec
INSERT INTO instance_score_revision_rows (
    revision_id,
    participant_id,
    participant_name,
    score,
    draft_points,
    bonus_points,
    total_points,
    points_available
)
SELECT
    $1,
    p.id,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM participants p
JOIN instances i ON i.id = p.instance_id
WHERE i.public_id = $8
  AND p.public_id = $9
`

type CreateInstanceScoreRevisionRowParams struct {
	RevisionID      int64       `json:"revision_id"`
	ParticipantName string      `json:"participant_name"`
	Score           int32       `json:"score"`
	DraftPoints     int32       `json:"draft_points"`
	BonusPoints     int32       `json:"bonus_points"`
	TotalPoints     int32       `json:"total_points"`
	PointsAvailable int32       `json:"points_available"`
	InstanceID      pgtype.UUID `json:"instance_id"`
	ParticipantID   pgtype.UUID `json:"participant_id"`
}

func (q *Queries) CreateInstanceScoreRevisionRow(ctx context.Context, arg CreateInstanceScoreRevisionRowParams) error {
	_, err := q.db.Exec(ctx, createInstanceScoreRevisionRow,
		arg.RevisionID,
		arg.ParticipantName,
		arg.Score,
		arg.DraftPoints,
		arg.BonusPoints,
		arg.TotalPoints,
		arg.PointsAvailable,
		arg.InstanceID,
		arg.ParticipantID,
	)
	return err
}

const getLatestInstanceScoreRevision = `-- name: GetLatestInstanceScoreRevision :one
SELECT
    isr.id,
    isr.public_id,
    isr.revision_number,
    isr.episode_number,
    isr.reason,
    isr.effective_at,
    isr.input_snapshot,
    isr.created_at
FROM instance_score_revisions isr
JOIN instances i ON i.id = isr.instance_id
WHERE i.public_id = $1
ORDER BY isr.revision_number DESC
LIMIT 1
`

type GetLatestInstanceScoreRevisionRow struct {
	ID             int64              `json:"id"`
	PublicID       pgtype.UUID        `json:"public_id"`
	RevisionNumber int32              `json:"revision_number"`
	EpisodeNumber  int32              `json:"episode_number"`
	Reason         string             `json:"reason"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	InputSnapshot  []byte             `json:"input_snapshot"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestInstanceScoreRevision(ctx context.Context, instanceID pgtype.UUID) (GetLatestInstanceScoreRevisionRow, error) {
	row := q.db.QueryRow(ctx, getLatestInstanceScoreRevision, instanceID)
	var i GetLatestInstanceScoreRevisionRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.RevisionNumber,
		&i.EpisodeNumber,
		&i.Reason,
		&i.EffectiveAt,
		&i.InputSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestInstanceScoreRevisionRows = `-- name: ListLatestInstanceScoreRevisionRows :many
WITH latest AS (
    SELECT isr.id, isr.public_id, isr.revision_number, isr.episode_number, isr.reason,
           isr.effective_at, isr.input_snapshot, isr.created_at
    FROM instance_score_revisions isr
    JOIN instances i ON i.id = isr.instance_id
    WHERE i.public_id = $1
    ORDER BY isr.revision_number DESC
    LIMIT 1
)
SELECT
    latest.public_id AS revision_id,
    latest.revision_number,
    latest.episode_number,
    latest.reason,
    latest.effective_at,
    latest.input_snapshot,
    latest.created_at AS revision_created_at,
    p.public_id AS participant_id,
    isrr.participant_name,
    isrr.score,
    isrr.draft_points,
    isrr.bonus_points,
    isrr.total_points,
    isrr.points_available
FROM latest
JOIN instance_score_revision_rows isrr ON isrr.revision_id = latest.id
JOIN participants p ON p.id = isrr.participant_id
ORDER BY isrr.total_points DESC, isrr.participant_name ASC
`

type ListLatestInstanceScoreRevisionRowsRow struct {
	RevisionID        pgtype.UUID        `json:"revision_id"`
	RevisionNumber    int32              `json:"revision_number"`
	EpisodeNumber     int32              `json:"episode_number"`
	Reason            string             `json:"reason"`
	EffectiveAt       pgtype.Timestamptz `json:"effective_at"`
	InputSnapshot     []byte             `json:"input_snapshot"`
	RevisionCreatedAt pgtype.Timestamptz `json:"revision_created_at"`
	ParticipantID     pgtype.UUID        `json:"participant_id"`
	ParticipantName   string             `json:"participant_name"`
	Score             int32              `json:"score"`
	DraftPoints       int32              `json:"draft_points"`
	BonusPoints       int32              `json:"bonus_points"`
	TotalPoints       int32              `json:"total_points"`
	PointsAvailable   int32              `json:"points_available"`
}

func (q *Queries) ListLatestInstanceScoreRevisionRows(ctx context.Context, instanceID pgtype.UUID) ([]ListLatestInstanceScoreRevisionRowsRow, error) {
	rows, err := q.db.Query(ctx, listLatestInstanceScoreRevisionRows, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestInstanceScoreRevisionRowsRow{}
	for rows.Next() {
		var i ListLatestInstanceScoreRevisionRowsRow
		if err := rows.Scan(
			&i.RevisionID,
			&i.RevisionNumber,
			&i.EpisodeNumber,
			&i.Reason,
			&i.EffectiveAt,
			&i.InputSnapshot,
			&i.RevisionCreatedAt,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.Score,
			&i.DraftPoints,
			&i.BonusPoints,
			&i.TotalPoints,
			&i.PointsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInstanceScoreRevisionNumber = `-- name: NextInstanceScoreRevisionNumber :one
SELECT COALESCE(MAX(isr.revision_number), 0)::INTEGER + 1 AS revision_number
FROM instance_score_revisions isr
JOIN instances i ON i.id = isr.instance_id
WHERE i.public_id = $1
`

func (q *Queries) NextInstanceScoreRevisionNumber(ctx context.Context, instanceID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextInstanceScoreRevisionNumber, instanceID)
	var revision_number int32
	err := row.Scan(&revision_number)
	return revision_number, err
}
