// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tribes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInstanceTribeMembershipsStartingAtOrAfter = `-- name: CountInstanceTribeMembershipsStartingAtOrAfter :one
SELECT COUNT(*)::bigint
FROM participant_group_membership_periods pgmp
JOIN participant_groups pg ON pg.id = pgmp.participant_group_id
JOIN instances i ON i.id = pg.instance_id
WHERE i.public_id = $1
  AND pg.kind = 'tribe'
  AND pgmp.starts_at >= $2
`

type CountInstanceTribeMembershipsStartingAtOrAfterParams struct {
	InstanceID pgtype.UUID        `json:"instance_id"`
	At         pgtype.Timestamptz `json:"at"`
}

func (q *Queries) CountInstanceTribeMembershipsStartingAtOrAfter(ctx context.Context, arg CountInstanceTribeMembershipsStartingAtOrAfterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInstanceTribeMembershipsStartingAtOrAfter, arg.InstanceID, arg.At)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const endInstanceTribeMembershipsAt = `-- name: EndInstanceTribeMembershipsAt :exec
UPDATE participant_group_membership_periods pgmp
SET ends_at = $1
FROM participant_groups pg, instances i
WHERE pg.id = pgmp.participant_group_id
  AND i.id = pg.instance_id
  AND i.public_id = $2
  AND pg.kind = 'tribe'
  AND pgmp.starts_at < $1
  AND (pgmp.ends_at IS NULL OR pgmp.ends_at > $1)
`

type EndInstanceTribeMembershipsAtParams struct {
	At         pgtype.Timestamptz `json:"at"`
	InstanceID pgtype.UUID        `json:"instance_id"`
}

func (q *Queries) EndInstanceTribeMembershipsAt(ctx context.Context, arg EndInstanceTribeMembershipsAtParams) error {
	_, err := q.db.Exec(ctx, endInstanceTribeMembershipsAt, arg.At, arg.InstanceID)
	return err
}

const getActivityOccurrenceBySourceRef = `-- name: GetActivityOccurrenceBySourceRef :one
SELECT
    ao.public_id AS id,
    ao.occurrence_type,
    ao.name,
    ao.effective_at,
    ao.status,
    ao.metadata
FROM activity_occurrences ao
JOIN instance_activities ia ON ia.id = ao.activity_id
WHERE ia.public_id = $1
  AND ao.source_ref = $2
`

type GetActivityOccurrenceBySourceRefParams struct {
	ActivityID pgtype.UUID `json:"activity_id"`
	SourceRef  pgtype.Text `json:"source_ref"`
}

type GetActivityOccurrenceBySourceRefRow struct {
	ID             pgtype.UUID        `json:"id"`
	OccurrenceType string             `json:"occurrence_type"`
	Name           string             `json:"name"`
	EffectiveAt    pgtype.Timestamptz `json:"effective_at"`
	Status         string             `json:"status"`
	Metadata       []byte             `json:"metadata"`
}

func (q *Queries) GetActivityOccurrenceBySourceRef(ctx context.Context, arg GetActivityOccurrenceBySourceRefParams) (GetActivityOccurrenceBySourceRefRow, error) {
	row := q.db.QueryRow(ctx, getActivityOccurrenceBySourceRef, arg.ActivityID, arg.SourceRef)
	var i GetActivityOccurrenceBySourceRefRow
	err := row.Scan(
		&i.ID,
		&i.OccurrenceType,
		&i.Name,
		&i.EffectiveAt,
		&i.Status,
		&i.Metadata,
	)
	return i, err
}

const listInstanceTribeMembershipsAt = `-- name: ListInstanceTribeMembershipsAt :many
SELECT
    pg.public_id AS participant_group_id,
    pg.name AS participant_group_name,
    p.public_id AS participant_id,
    p.name AS participant_name,
    pgmp.starts_at
FROM participant_group_membership_periods pgmp
JOIN participant_groups pg ON pg.id = pgmp.participant_group_id
JOIN participants p ON p.id = pgmp.participant_id
JOIN instances i ON i.id = pg.instance_id
WHERE i.public_id = $1
  AND pg.kind = 'tribe'
  AND pgmp.starts_at <= $2
  AND (pgmp.ends_at IS NULL OR pgmp.ends_at > $2)
ORDER BY pg.name ASC, p.name ASC
`

type ListInstanceTribeMembershipsAtParams struct {
	InstanceID pgtype.UUID        `json:"instance_id"`
	At         pgtype.Timestamptz `json:"at"`
}

type ListInstanceTribeMembershipsAtRow struct {
	ParticipantGroupID   pgtype.UUID        `json:"participant_group_id"`
	ParticipantGroupName string             `json:"participant_group_name"`
	ParticipantID        pgtype.UUID        `json:"participant_id"`
	ParticipantName      string             `json:"participant_name"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
}

func (q *Queries) ListInstanceTribeMembershipsAt(ctx context.Context, arg ListInstanceTribeMembershipsAtParams) ([]ListInstanceTribeMembershipsAtRow, error) {
	rows, err := q.db.Query(ctx, listInstanceTribeMembershipsAt, arg.InstanceID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInstanceTribeMembershipsAtRow{}
	for rows.Next() {
		var i ListInstanceTribeMembershipsAtRow
		if err := rows.Scan(
			&i.ParticipantGroupID,
			&i.ParticipantGroupName,
			&i.ParticipantID,
			&i.ParticipantName,
			&i.StartsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
