// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wordle_rounds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWordleRound = `-- name: CreateWordleRound :one
INSERT INTO wordle_rounds (
    activity_id,
    activity_occurrence_id,
    round_key,
    opens_at,
    cutoff_at
)
SELECT
    ia.id,
    ao.id,
    $1,
    $2,
    $3
FROM instance_activities ia
JOIN activity_occurrences ao
  ON ao.public_id = $4
 AND ao.activity_id = ia.id
WHERE ia.public_id = $5
RETURNING (
    SELECT public_id
    FROM activity_occurrences
    WHERE id = wordle_rounds.activity_occurrence_id
) AS id
`

type CreateWordleRoundParams struct {
	RoundKey             string             `json:"round_key"`
	OpensAt              pgtype.Timestamptz `json:"opens_at"`
	CutoffAt             pgtype.Timestamptz `json:"cutoff_at"`
	ActivityOccurrenceID pgtype.UUID        `json:"activity_occurrence_id"`
	ActivityID           pgtype.UUID        `json:"activity_id"`
}

func (q *Queries) CreateWordleRound(ctx context.Context, arg CreateWordleRoundParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWordleRound,
		arg.RoundKey,
		arg.OpensAt,
		arg.CutoffAt,
		arg.ActivityOccurrenceID,
		arg.ActivityID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getWordleRound = `-- name: GetWordleRound :one
SELECT
    ao.public_id AS id,
    i.public_id AS instance_id,
    ia.public_id AS activity_id,
    ia.activity_type,
    ao.occurrence_type,
    ao.status AS occurrence_status,
    ao.effective_at,
    ao.name,
    wr.round_key,
    wr.opens_at,
    wr.cutoff_at,
    wr.closed_at,
    wr.resolution_response,
    wr.created_at,
    wr.updated_at
FROM wordle_rounds wr
JOIN activity_occurrences ao ON ao.id = wr.activity_occurrence_id
JOIN instance_activities ia ON ia.id = wr.activity_id
JOIN instances i ON i.id = ia.instance_id
WHERE ao.public_id = $1
`

type GetWordleRoundRow struct {
	ID                 pgtype.UUID        `json:"id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	ActivityID         pgtype.UUID        `json:"activity_id"`
	ActivityType       string             `json:"activity_type"`
	OccurrenceType     string             `json:"occurrence_type"`
	OccurrenceStatus   string             `json:"occurrence_status"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	Name               string             `json:"name"`
	RoundKey           string             `json:"round_key"`
	OpensAt            pgtype.Timestamptz `json:"opens_at"`
	CutoffAt           pgtype.Timestamptz `json:"cutoff_at"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
	ResolutionResponse []byte             `json:"resolution_response"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWordleRound(ctx context.Context, id pgtype.UUID) (GetWordleRoundRow, error) {
	row := q.db.QueryRow(ctx, getWordleRound, id)
	var i GetWordleRoundRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ActivityID,
		&i.ActivityType,
		&i.OccurrenceType,
		&i.OccurrenceStatus,
		&i.EffectiveAt,
		&i.Name,
		&i.RoundKey,
		&i.OpensAt,
		&i.CutoffAt,
		&i.ClosedAt,
		&i.ResolutionResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWordleRoundByActivityAndKey = `-- name: GetWordleRoundByActivityAndKey :one
SELECT
    ao.public_id AS id,
    i.public_id AS instance_id,
    ia.public_id AS activity_id,
    ia.activity_type,
    ao.occurrence_type,
    ao.status AS occurrence_status,
    ao.effective_at,
    ao.name,
    wr.round_key,
    wr.opens_at,
    wr.cutoff_at,
    wr.closed_at,
    wr.resolution_response,
    wr.created_at,
    wr.updated_at
FROM wordle_rounds wr
JOIN activity_occurrences ao ON ao.id = wr.activity_occurrence_id
JOIN instance_activities ia ON ia.id = wr.activity_id
JOIN instances i ON i.id = ia.instance_id
WHERE ia.public_id = $1
  AND wr.round_key = $2
`

type GetWordleRoundByActivityAndKeyParams struct {
	ActivityID pgtype.UUID `json:"activity_id"`
	RoundKey   string      `json:"round_key"`
}

type GetWordleRoundByActivityAndKeyRow struct {
	ID                 pgtype.UUID        `json:"id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	ActivityID         pgtype.UUID        `json:"activity_id"`
	ActivityType       string             `json:"activity_type"`
	OccurrenceType     string             `json:"occurrence_type"`
	OccurrenceStatus   string             `json:"occurrence_status"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	Name               string             `json:"name"`
	RoundKey           string             `json:"round_key"`
	OpensAt            pgtype.Timestamptz `json:"opens_at"`
	CutoffAt           pgtype.Timestamptz `json:"cutoff_at"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
	ResolutionResponse []byte             `json:"resolution_response"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWordleRoundByActivityAndKey(ctx context.Context, arg GetWordleRoundByActivityAndKeyParams) (GetWordleRoundByActivityAndKeyRow, error) {
	row := q.db.QueryRow(ctx, getWordleRoundByActivityAndKey, arg.ActivityID, arg.RoundKey)
	var i GetWordleRoundByActivityAndKeyRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ActivityID,
		&i.ActivityType,
		&i.OccurrenceType,
		&i.OccurrenceStatus,
		&i.EffectiveAt,
		&i.Name,
		&i.RoundKey,
		&i.OpensAt,
		&i.CutoffAt,
		&i.ClosedAt,
		&i.ResolutionResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWordleRound = `-- name: LockWordleRound :one
SELECT
    ao.public_id AS id,
    i.public_id AS instance_id,
    ia.public_id AS activity_id,
    ia.activity_type,
    ao.occurrence_type,
    ao.status AS occurrence_status,
    ao.effective_at,
    ao.name,
    wr.round_key,
    wr.opens_at,
    wr.cutoff_at,
    wr.closed_at,
    wr.resolution_response,
    wr.created_at,
    wr.updated_at
FROM wordle_rounds wr
JOIN activity_occurrences ao ON ao.id = wr.activity_occurrence_id
JOIN instance_activities ia ON ia.id = wr.activity_id
JOIN instances i ON i.id = ia.instance_id
WHERE ao.public_id = $1
FOR UPDATE OF wr
`

type LockWordleRoundRow struct {
	ID                 pgtype.UUID        `json:"id"`
	InstanceID         pgtype.UUID        `json:"instance_id"`
	ActivityID         pgtype.UUID        `json:"activity_id"`
	ActivityType       string             `json:"activity_type"`
	OccurrenceType     string             `json:"occurrence_type"`
	OccurrenceStatus   string             `json:"occurrence_status"`
	EffectiveAt        pgtype.Timestamptz `json:"effective_at"`
	Name               string             `json:"name"`
	RoundKey           string             `json:"round_key"`
	OpensAt            pgtype.Timestamptz `json:"opens_at"`
	CutoffAt           pgtype.Timestamptz `json:"cutoff_at"`
	ClosedAt           pgtype.Timestamptz `json:"closed_at"`
	ResolutionResponse []byte             `json:"resolution_response"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockWordleRound(ctx context.Context, id pgtype.UUID) (LockWordleRoundRow, error) {
	row := q.db.QueryRow(ctx, lockWordleRound, id)
	var i LockWordleRoundRow
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ActivityID,
		&i.ActivityType,
		&i.OccurrenceType,
		&i.OccurrenceStatus,
		&i.EffectiveAt,
		&i.Name,
		&i.RoundKey,
		&i.OpensAt,
		&i.CutoffAt,
		&i.ClosedAt,
		&i.ResolutionResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWordleRoundClosedAt = `-- name: UpdateWordleRoundClosedAt :one
UPDATE wordle_rounds wr
SET closed_at = COALESCE(wr.closed_at, $1),
    updated_at = NOW()
FROM activity_occurrences ao
WHERE wr.activity_occurrence_id = ao.id
  AND ao.public_id = $2
RETURNING wr.closed_at, wr.updated_at
`

type UpdateWordleRoundClosedAtParams struct {
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
	ID       pgtype.UUID        `json:"id"`
}

type UpdateWordleRoundClosedAtRow struct {
	ClosedAt  pgtype.Timestamptz `json:"closed_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWordleRoundClosedAt(ctx context.Context, arg UpdateWordleRoundClosedAtParams) (UpdateWordleRoundClosedAtRow, error) {
	row := q.db.QueryRow(ctx, updateWordleRoundClosedAt, arg.ClosedAt, arg.ID)
	var i UpdateWordleRoundClosedAtRow
	err := row.Scan(&i.ClosedAt, &i.UpdatedAt)
	return i, err
}

const updateWordleRoundResolution = `-- name: UpdateWordleRoundResolution :one
UPDATE wordle_rounds wr
SET resolution_response = $1,
    updated_at = NOW()
FROM activity_occurrences ao
WHERE wr.activity_occurrence_id = ao.id
  AND ao.public_id = $2
RETURNING wr.resolution_response, wr.updated_at
`

type UpdateWordleRoundResolutionParams struct {
	ResolutionResponse []byte      `json:"resolution_response"`
	ID                 pgtype.UUID `json:"id"`
}

type UpdateWordleRoundResolutionRow struct {
	ResolutionResponse []byte             `json:"resolution_response"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWordleRoundResolution(ctx context.Context, arg UpdateWordleRoundResolutionParams) (UpdateWordleRoundResolutionRow, error) {
	row := q.db.QueryRow(ctx, updateWordleRoundResolution, arg.ResolutionResponse, arg.ID)
	var i UpdateWordleRoundResolutionRow
	err := row.Scan(&i.ResolutionResponse, &i.UpdatedAt)
	return i, err
}
