apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: castaway
  namespace: argocd
spec:
  description: Castaway self-hosted applications
  sourceRepos:
    - https://github.com/bry-guy/srvivor.git
  destinations:
    - namespace: castaway
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
