apiVersion: v1
kind: Service
metadata:
  name: castaway-postgres
  labels:
    app.kubernetes.io/name: castaway-postgres
    app.kubernetes.io/part-of: castaway
spec:
  selector:
    app.kubernetes.io/name: castaway-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
