name: DevPod Prebuild

on:
  workflow_run:
    workflows: ["Build and Publish Dev Container"]
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/devpod-prebuild.yml'
      - '.devcontainer/**'
      - 'mise.toml'
  workflow_dispatch:  

jobs:
  prebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Install DevPod CLI
        run: |
          curl -L -o devpod https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64
          chmod +x devpod
          sudo mv devpod /usr/local/bin
      
      - name: Create and Push Prebuild
        run: |
          devpod provider add docker
          devpod build . --repository=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} --platform linux/amd64 --debug
